### ISSUE TITLE
Segment data disappears from UI after changing auto_archive setting

### ISSUE THREAD

**Issue by mgonera** [matomo-org/matomo#10036]
Segment data disappears from UI after changing auto_archive setting from 0 to 1. After changing back, data appears again. Version 2.16. Please see attached video:

https://drive.google.com/a/piwik.pro/file/d/0B2rhGHbcCX73dmMtSUJUdHRBQzQ/view?usp=sharing

One has to be logged in with piwik.pro credentials to view it.

FYI @mattab

**Comment by tsteur** [comment]
Is config `browser_archiving_disabled_enforce` disabled or enabled?

**Comment by tsteur** [comment]
FYI: I tried to reproduce it but couldn't. I reckon it'd be could to know config settings of this instance.

**Comment by quba** [comment]
For sure `process_new_segments_from = "segment_last_edit_time"``

**Comment by tsteur** [comment]
Cheers, I had a rough look at the code and this *should* only affect the cron archiver but not when requesting report via API / UI. Be good to know some more config settings and then I'll try to reproduce again

**Comment by mgonera** [comment]
@tsteur `browser_archiving_disabled_enforce = 1`

let me know what else you may need

**Comment by tsteur** [comment]
Ideally pretty much all settings customized (meaning in `config.ini.php` or `common.ini.php`) except `Plugins`, `PluginsInstalled`, `Database`, `trusted_hosts`, `salt` and whatever contains private data. EG

`time_before_today_archive_considered_outdated`, `archiving_range_force_on_browser_request`, `purge_date_range_archives_after_X_days`, `always_archive_*`, `

**Comment by tsteur** [comment]
@quba I think you mentioned you can reproduce it somewhere as well? Is it the same setup?

The data viewed, is it today?

**Comment by mgonera** [comment]
@tsteur 

`[tests]
enable_create_realtime_segment = 0
​
[log]
log_only_when_cli = 1
​
[General]
browser_archiving_disabled_enforce = 1
time_before_today_archive_considered_outdated = 60000
force_ssl = 0
salt = "redacted"
enable_fingerprinting_across_websites = 1
enable_load_data_file = 0`

**Comment by tsteur** [comment]
Do you know if range periods are archived on that instance? eg `archiving_range_force_on_browser_request`

**Comment by tsteur** [comment]
After investigating and discussing with @quba here's a summary:

When archiving a segment (or any other archives) via cron archiver, global done flags seem to be set. When archiving via browser, a done flag is generated for each plugin see https://github.com/piwik/piwik/blob/2.16.1/core/ArchiveProcessor/Rules.php#L52-L55 which is based on whether a segment is pre-processed (auto-archived) when requesting data ranges https://github.com/piwik/piwik/blob/2.16.1/core/ArchiveProcessor/Rules.php#L60-L64

This means when switching to "Real time processing" and requesting a "date range" or a "segment", it would not re-use existing pre-processed archives. It will try to re-archive them and generate done flags with the plugin name.

This should be usually not a problem but it can be a problem when real time archiving via browser is disabled (@mgonera use case as `browser_archiving_disabled_enforce = 1`) or when either instance or date range is quite big and the archiving process runs out of time or memory. Then it will not show data for all the days.

It's not directly a bug but something we can improve to make it more stable for this use case.
To fix this we could check always for both global and plugin done flag in such a case maybe? First for the regular plugin done flag which should exist in most cases, if not found we look for a finished global done flag and reuse that data. We wouldn't be able to use a temporary global done flag since it might not contain all data. We could also always generate done flags with plugin names but this would result in many more entries in the DB etc.

@mattab do you have any thoughts?

**Comment by quba** [comment]
In short words: browser archiving does not create a global done flag for a given segment (because it triggers archiving for all plugins one by one on demand and creates a done flag for a given segment AND plugin). Segments set to be pre-archived use only the global done flag.

**Comment by tsteur** [comment]
Actually, I think by further looking into the code it seems to be partially implemented but maybe it doesn't really work somewhere. It runs this code path and searches for all done flags when browser archiving is disabled: https://github.com/piwik/piwik/blob/2.16.1/core/ArchiveProcessor/Rules.php#L104-L110 . It seems to not look for all done flags when browser archiving is enabled.

**Comment by tsteur** [comment]
FYI: I need to have a look again tomorrow

**Comment by tsteur** [comment]
ping @mattab

**Comment by tsteur** [comment]
FYI: I debugged with all kinda settings and was finally able to reproduce with following config: 

```
[General]
enable_browser_archiving_triggering = 0
browser_archiving_disabled_enforce = 1
archiving_range_force_on_browser_request = 1
```
In my case I had to disable option `enableBrowserTriggerArchiving` in `piwik_option` table because general settings admin is enabled instead of using `enable_browser_archiving_triggering`. The settings admin UI might be disabled on the clients instance and config will be used. It was always fetching both done flags but it was only looking for the plugin done flag when segment and / or range is used. I need to see whether I regress anything else with this solution.

**Comment by mgonera** [comment]
@tsteur so what would be workaround for now? enable enable_browser_archiving_triggering ?

**Comment by tsteur** [comment]
You might also have to set `browser_archiving_disabled_enforce=0` in case value is `0`, then it should work as a workaround. But UI will become slower as it will archive during browser request most of the times. I issued a PR that should fix it

**Comment by quba** [comment]
This fix will also affect segment? I've just fixed similar issue with segment. After a successful archiving, I had to delete the following archive flags to fix it:
```
delete from piwik_archive_numeric_2016_05 where idsite = X and name like '%segmenthash.%';
```

**Comment by tsteur** [comment]
It should also affect segments, yes

**Comment by mattab** [comment]
Cannot reproduce in 2.16.2 after applying patch, please re-open if/when you know how to reproduce this issue :+1:

**Comment by RMastop** [comment]
I encounter the same thing; on an instance, having loads of data. The segmented data previously visible disappears after switching the segments to pre-processing.
I guess the fix from @tsteur does not work on already processed data from before the upgrade?

**Comment by mattab** [comment]
I think this issue is still here, I'm re-opening the ticket so we investigate further. I'll talk to a user this week who experiences this. 

Does anyone else still have this issue in 2.16.2?

**Comment by mgonera** [comment]
How we were able to deal with this issue, was to clear existing archives and rearchive the data. It worked, so we suppose there was some error in archives themselves. Can this be a possibility?

**Comment by RMastop** [comment]
Thanks @mgonera,
This is indeed the workaround I use. It works, as long as you have the historic raw data in logs tables available.

**Comment by mattab** [comment]
Richard you mention it is a "workaround", so @mgonera @RMastop you mean the bug is not actually fully fixed, right?

**Comment by mgonera** [comment]
Yes but it seems is random occurrence and may be hard to reproduce.

Michael Gonera
Project Coordinator
Piwik PRO - Premium functionality and enterprise-level support for Piwik
Analytics.

**Comment by mattab** [comment]
Ok, good to know the bug is not actually fixed. we will need to fix it :ok:

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please open a new fresh issue :+1:  Thanks!
