### ISSUE TITLE
most accessible segment filters in demo without result

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10068]
most accessible segment filters in demo have no result
please see attachment

would be good to show only "working" and usefull examples here...
![2016-04-18_16h06_20](https://cloud.githubusercontent.com/assets/5681880/14606993/01e1c990-0580-11e6-80b4-f0016deec2aa.png)

**Comment by tsteur** [comment]
👍 I reckon these segments used to work but not anymore after moving to the new forum

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
