### ISSUE TITLE
Ability to match Goal by Category, Action AND name

### ISSUE THREAD

**Issue by vercotux** [matomo-org/matomo#10133]
Currently it is only possible to specify 1 of the following 3 criteria, when adding a goal triggered on "Send an event":
- Category
- Action
- Name

There needs to be a way to set all 3 simultaneously, not only one.

**Comment by tsteur** [comment]
That would be a good new feature to have. In the meanwhile you can 

1) trigger a goal manually http://developer.piwik.org/guides/tracking-javascript-guide#manually-trigger-goal-conversions
2) develop a custom plugin using PHP (it is already possible to do this in a plugin but would be a bit fragile and hard since the methods to do this are not a public API)

**Comment by vercotux** [comment]
Goal IDs are not ideal for this. They cant be manually set in Piwik so they are very inconvenient to work with. The best way to overcome this is to rely on the event 'name'. Specify a unique name for every event and then trigger goals based on them.

**Comment by LeoniePhiline** [comment]
This could be a great feature in 2022, what do you think?

**Comment by mattab** [comment]
Duplicates this: https://github.com/matomo-org/matomo/issues/10791
