### ISSUE TITLE
several plugin updates available: "update all"-Button

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10488]
When there are several plugin updates available, it would be handy to not have to do the update procedure step by step for each available update but all in one with a Button/Link "update all"

at the end of the procedure there should be summary shown e.g. "x plugins were updated"

**Comment by mattab** [comment]
Thanks @hpvd for the suggestion! wanted to create this issue for a while as well :+1:

**Comment by mattab** [comment]
@tsteur has made some progress on this, but it's not quite yet implemented.

**Comment by mattab** [comment]
So currently very nicely we update all plugins when Matomo core is being auto-updated. 

But sometimes it takes 1-2-3 months for a Matomo release to come out and in the meantime there may be several plugin upgrades. Or the license key was invalid and then the license is renewed so one can update all plugis. So quite often one can get this wall of upgrades screen:

![update screen](https://user-images.githubusercontent.com/466765/45060872-09f08080-b0f6-11e8-9167-a7fefd5b3ef6.png)

The simplest and sufficient solution would be to have a button "Update all plugins". In this example (14 plugins to upgrade), it would save probably 5-7 minutes of time clicking and waiting a lot (because the nonce invalidates after each uninstall we have to reload the page listing all plugins).

It would be good to have a message that clearly says "Downloading and updating all plugins, this will only take a minute..."

Also, useful but not required, Wordpress does it nicely where you can select which plugins to upgrade:

![plugins](https://user-images.githubusercontent.com/466765/45061081-04e00100-b0f7-11e8-9fef-9d2d44a6a2c9.png)
