### ISSUE TITLE
For Apache2 servers, AllowOverride is required for Icons to display -> update documentations

### ISSUE THREAD

**Issue by 4A4B** [matomo-org/matomo#10672]
I have installed the Official Debian Package for Piwik on Debian Jessie. After the update of piwik to version 2.16.3 the icons in the backend were missing. The error log of the webserver showed this error message:

> /usr/share/piwik/plugins/.htaccess: AddHandler not allowed here

This refers to this code in the file /usr/share/piwik/plugins/.htaccess:

```
# Serve HTML files as text/html mime type - Note: requires mod_mime apache module!
<IfModule mod_mime.c>
   AddHandler text/html .html
   AddHandler text/html .htm
</IfModule>
```

mod_mime was already enabled, but the addhandler directive not allowed in the .htaccess file
 because of the directive "AllowOverride Limit" in my VirtualHost configuration; after I changed this to an "AllowOverride All" and reloaded the webserver the backend was OK again.

Perhaps it would be good to write in the requirements that an "AllowOverride All" is necessary? 

http://piwik.org/docs/requirements/

**Comment by 4A4B** [comment]
Important amendment:

"AllowOverride All" is not necessary, "AllowOverride AuthConfig Limit FileInfo" is sufficient and more secure

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
