### ISSUE TITLE
How do I get LOAD DATA INFILE to work on my server?

### ISSUE THREAD

**Issue by pBartels** [matomo-org/matomo#10732]
http://piwik.org/faq/troubleshooting/#faq_194 describes what to do if the system report warns that LOAD DATA INFILE is not usable.

In fact, LOAD DATA INFILE does work on our infrastructure but it seems piwik is not passing the appropiate client flags to mysql_connect, when connecting to the mysql server.
see http://php.net/manual/de/mysql.constants.php#mysql.client-flags and http://dev.mysql.com/doc/refman/5.7/en/load-data-local.html#c5457

Passing the correct client flags during connection would allow the usage of LOAD DATA LOCAL INFILE.

Thanks.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

See also: https://matomo.org/faq/troubleshooting/faq_194/
