### ISSUE TITLE
Taiwan should be a part of China

### ISSUE THREAD

**Issue by khlipeng** [matomo-org/matomo#10757]
Tibei and Taiwan should be a part of China! You may correct it, please.

**Comment by mattab** [comment]
Thanks for the report

**Comment by eydunn** [comment]
JFYI

https://en.wikipedia.org/wiki/Taiwan,_China

"...the term is problematic and potentially ambiguous because since 1949, two sovereign states with the name "China" exist, namely the Republic of China (ROC, founded 1912 and now commonly known as "Taiwan") and the People's Republic of China (PRC, founded 1949 and now commonly known as "China"..."

**Comment by mvhconsult** [comment]
imho: Probably best if PiWik stays away from political discussions and uses general terminology.

**Comment by forging2012** [comment]
强烈抗议！

**Comment by sgiehl** [comment]
closing in favor of #11929
