### ISSUE TITLE
some broken/non good things before/during setting up geoip

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#11006]
some broken things before/during setting up geoip in latest stable Piwik (2.17.1):
1. [fixed with P3.0 see https://github.com/piwik/piwik/issues/11006#issuecomment-267133495]
broken design (too large font, FF 50.1)
please see attachment 
2. url shown of free  DB without only http instead of https (which works perfect for download)
please see attachment
3. url has to be copied which is uncomfortable: would be better to have a button "use this"
4. after setting up, one get a date at least one week in the future when it's downloaded first time - should be immediately (otherwise there is no geoip function for at least a week)
please see attachment

![2016-12-14_14h33_50](https://cloud.githubusercontent.com/assets/5681880/21184606/7aa83f7c-c20d-11e6-8760-c096b47e5ffa.png)
![2016-12-14_14h57_28](https://cloud.githubusercontent.com/assets/5681880/21184674/d582e776-c20d-11e6-95af-7faf484f5fb5.png)

**Comment by tsteur** [comment]
FYI: It looks fine with Piwik 3

![image](https://cloud.githubusercontent.com/assets/273120/21197725/5f399cec-c2a1-11e6-95cb-cba7ef275161.png)

and some links are clickable here. However they are still `http`. That's because some user's server might not be able to connect to HTTPS websites and the same URL is currently used by the server and shown in the UI. It should be an easy fix to make it all HTTPS in the UI

**Comment by mattab** [comment]
FYI The only remaining item to do in this ticket seems to be: `after setting up, one get a date at least one week in the future when it's downloaded first time - should be immediately (otherwise there is no geoip function for at least a week)`
