### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by NimaHp** [matomo-org/matomo#11206]
When there's some persian characters like "ف" and "ح" in url query of request, response will be "400 Bad Request"! (no problem in action_name)
Using latest piwik (3.0.1) on Windows Server 2012 r2, iis 8.5 and PHP 7.1 x64

**Comment by mattab** [comment]
Hello @MrDevIr 
Could you please post a sample Web server acces log file which triggers a 400 error? it would be great to see exactly which piwik.php?.... request triggers errors. We'll investigate then

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
