### ISSUE TITLE
Overlay doesn't work

### ISSUE THREAD

**Issue by ctuxboy** [matomo-org/matomo#11260]
![1335090dbc5d40fe56be38c202b147ade9eae521](https://cloud.githubusercontent.com/assets/10013632/22196052/8f8b6416-e14b-11e6-9e22-5d1ec529d563.png)

See topic: https://forum.piwik.org/t/piwik-page-overlay-option/22754

**Comment by axelhahn** [comment]
What is the HTTP reponse header in "Personal Health plan" website? 
Is there a restriction "X-Frame..." that disallows putting the website into a frame?

**Comment by ctuxboy** [comment]
Hi axelhahn,
I test it on this website: http://web-sniffer.net/
But can't see any restrictions or disallow frames.

**Comment by axelhahn** [comment]
Hi Ctuxboy, 

ah I see .. but I think you need to check where the error message in the console come from. 

There one is labeled "Invalid X-Frame options". The web content istelf is visible in the screenshot - so it cannot be the X-Frame option in http header of the website.
This message is related to a request to http://192.168.0.234. (My mistake I didn't look carefully enough)

And the other red message is "ERR_CONNECTION_REFUSED". This can be because of an adblocker/ adnauseam/ microblock addon. Can you disable all for a moment (or use another webbrowser)?

good luck,
Axel

**Comment by mattab** [comment]
@ctuxboy did you check the various options in: https://piwik.org/docs/page-overlay/#page-overlay-troubleshooting

**Comment by ctuxboy** [comment]
Hi, sorry for the late feedback. But no i don't tested yet.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!

**Comment by ctuxboy** [comment]
Hi guys, sorry for the very late feedback.
I recieved a notifify in my mailbox about the issue.
The website doesn't exists anymore.
Sorry about that!
