### ISSUE TITLE
Chrome Page unresponsive with date range + segments

### ISSUE THREAD

**Issue by gaumondp** [matomo-org/matomo#11406]
With pre-crunched reports, everything run smoothly but my Piwik installation has more than 130 milllion records so when using segments AND Date Range I often got the infamous "Page(s) unresponsive" in Chrome because Piwik is hard at work getting the data.

This kind of timeout doesn't seems to show up in Opera or recent Firefox. It looks like since Piwik isn't sending any data for a long time (3 minutes) Chrome got the impression nothing is happening and throw the "Unresponsive" box. 

Feature request: Send some stuff from the server to say "I'm still working, no worries" to browsers...

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
