### ISSUE TITLE
Compatibility of Piwik with MySQL 5.7.17 in group replication 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#11596]
Reported by email:

When MySQL 5.7.17 is running in group replication (a feature introduced in MySQL 5.7.17), all tables are required to have a primary key. Installing Piwik 3.0.3 on MySQL 5.7.17 running in a group replication settings, the replication breaks the group because all of the Piwik tables do not contain a primary key. The solution is to add a primary key to the three Piwik tables that do not contain primary keys:

piwik_log_profiling
piwik_plugin_setting
piwik_site_setting

**Comment by ArdvarkGit** [comment]
When MySQL 5.7.17 is running in group replication (a high-availability feature introduced in MySQL 5.7.17), all tables are required to have a primary key. Installing Piwik 3.0.3 on MySQL 5.7.17 running in a group replication breaks the group because all of the Piwik tables do not contain a primary key. The solution is to add a primary key to the three Piwik tables that do not contain primary keys:

- piwik_log_profiling
- piwik_plugin_setting
- piwik_site_setting

Reference: [https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html](https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html)
"Primary Keys. Every table that is to be replicated by the group must have an explicit primary key defined. Primary keys play an extremely important role in determining which transactions conflict by identifying exactly which rows each transaction has modified."
