### ISSUE TITLE
forum signup/login via github auth

### ISSUE THREAD

**Issue by mpaolo** [matomo-org/matomo#11590]
signup/login in piwik forum via github method fails for me (and at least another guy: https://forum.piwik.org/t/forum-error-when-signing-up-with-github/22932) - I get the following msg in either case, and have no clues where to look for in my github account to 'approve auth' (for piwik?):

"Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? "

**Comment by mattab** [comment]
Thanks for the report, it has been fixed and you can login with Github on the forums :+1:

**Comment by RafalLukawiecki** [comment]
Sorry for commenting on a closed issue, @mattab, but I am experiencing the same, since the change from Piwik to Matomo. Is there some reset that is necessary to use our Github accounts to reauthorise with Matomo forums? I tried revoking in Github, too, but I do not get a chance to reauthorize in Matomo forums, always the above error. Thank you.

**Comment by Findus23** [comment]
@RafalLukawiecki 
Hi,
I just tested it and indeed the github login is broken. (probably because of the domain change).

In the meantime until it is fixed, there is another way to login:
The discourse accounts are just linked to the E-Mail address. So you should be able to use "forgot password" enter your email and login that way. 
The github login will stay and you will be able to login with it or with email and password in the furture.

If something doesn't work, please contact me at lukas@matomo.org and I'll help you.

**Comment by mattab** [comment]
Should now work, let us know if you still have issues with forum social logins

**Comment by RafalLukawiecki** [comment]
Yes, it works again, I have just checked. Many thanks @Findus23 and @mattab.

**Comment by mpaolo** [comment]
there's seems a regression here, I'm no more able so login to piwik/matomo via github, keeps on cycling for new account etc :/

**Comment by Findus23** [comment]
@mpaolo I was able to sign up with with Github and now login via Github without issues.

You could try signing up with the E-Mail you are using for Github, because then you can simply sign in with the Github login afterwards.
