### ISSUE TITLE
RowActions of SubdataTables (nodes) with many rows are disabled when limit selector is set to >=250

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#11647]
This is not reproducible on the demo since there is no SubdataTables hitting the set limit.

**Comment by tsteur** [comment]
This is because of https://github.com/piwik/piwik/pull/11308 . We could maybe remove it once it is >= 500 but would need to test again re performance.

Problem is the more rows are shown the slower the UI gets and becomes eventually unusable. Like it will take even with only few hundred rows sometimes seconds to load and each scroll may take seconds. Ideally we would make it faster but it is not trivial I reckon or takes some time.

**Comment by mattab** [comment]
@tsteur is this limitation still in place?

**Comment by tsteur** [comment]
I think it's fixed. At least can't find it in the code anymore.
