### ISSUE TITLE
URL's with IDN shows in Punycode

### ISSUE THREAD

**Issue by aXe1** [matomo-org/matomo#11640]
I'm using official Piwik docker container on cyrillic domain `.рф`.
Every tracked URL shows in Punycode.
I think it isn't expected behavior. Is there are some config option to always show urls in Unicode?
Already tried to search in docs, code, issues - couldn't find any related info, sorry.

**Comment by mattab** [comment]
Hi @aXe1 Can you post a screenshot showing what you are seeing, and what did you expect instead?

**Comment by aXe1** [comment]
In every URL shoud be cyrillic `пример.рф` instead of `xn--e1afmkfd.xn--p1ai` (Punycode).

![screenshot from 2017-05-09 17-09-26](https://cloud.githubusercontent.com/assets/276515/25855104/e7a3eac8-34da-11e7-8a47-ccbc4f7a6575.png)

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
