### ISSUE TITLE
Page overlay not loading

### ISSUE THREAD

**Issue by mandydjr** [matomo-org/matomo#11768]
Hi

We are using Piwik Community version 2.14.3.
The latest Piwik Community version is 3.0.4

The page overlay function was working when I last checked on 25 May, then it was no longer working on 31 May.

The other reporting is working. When I choose the page overlay report the left hand nav just reads "Loading" and the error message "The server refused the connection" shows in the part of the page where the intranet page with overlay usually sits .
Can anyone assist?

cheers

![piwik1](https://cloud.githubusercontent.com/assets/29111256/26766546/65583814-49d7-11e7-8233-494e52c741bf.png)

**Comment by mattab** [comment]
Can you please send us this Piwik URL + login + password + link to this issue at https://piwik.org/contact/ and we'll take a look

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
