### ISSUE TITLE
Selected evolution metrics get reset on period change

### ISSUE THREAD

**Issue by pwagner** [matomo-org/matomo#11899]
We are using the latest Piwik release (3.0.4), and the following behaviour did not occur with previous versions:
In the visualization "Evolution over the period" (e.g. the chart on the top of Referrers > Overview), the metrics that were manually selected disappear, when the period is changed.

This gif demonstrates the issue:
![Evolution Metrics Issue](https://media.giphy.com/media/3ohzgOJQNUt0KExBpC/giphy.gif)

I selected the metric "Unique visitors", and then changed the period from "week" to "month".
"Unique visitors" is no longer displayed, only the default metric of "Visits".

It looks like the selection of evolution metrics is lost, when the time range is changed.
Expected behaviour: The evolution metrics should stay selected.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
