### ISSUE TITLE
Page Overlay and token authentication

### ISSUE THREAD

**Issue by pitchfol** [matomo-org/matomo#11901]
Page overlay works when logged in. Using an authentication token works with all other API requests.

When passing an authentication token with the page overlay, the browser asks the user to login and the token is stripped out of the API call.

I have tested this on the latest Piwik release on a local instance, AWS EC2 and innocraft.cloud.

I have also amended Piwik config to disable the iframe overlay and the issue did not clear.

The API is the same domain and /Piwik was always installed to the root of the domain.

Changing access to anonymous resolves the issue, but doesn't fix the problem and I can't run this service without authentication.

Hoping this can be resolved very quickly in the community.

**Comment by pitchfol** [comment]
The test is a basic HTML with no scripts used. Just pageA>href>pageB.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). Ideally post screenshots of what you see and any browser console message. We will gladly take a look again!
