### ISSUE TITLE
Run automated tests against PHP 7.3 to ensure full compatibility

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#11936]
In PHP 7.2 some new methods will be deprecated and trigger notices see https://devzone.zend.com/7628/deprecations-php-7-2/

I have noticed eg `create_function()` is being used and `$php_errormsg`. Didn't check all deprecated functions. Goal would be to update libs and code needed to not get any notices.

**Comment by mattab** [comment]
See also this issue in Sparklines: #12065

**Comment by mattab** [comment]
* Probably we would need to enable the CI builds to run on PHP 7.2

**Comment by mneudert** [comment]
_Just some thoughts on the CI_

Would if be a possible solution to use a cron trigger for "non-minimum PHP versions" like 7.x?

Using a special repository containing only one branch for each PHP version with a custom `.travis.yml` could trigger specific builds without completely overloading Travis. Using a special repository avoids messing with branching on the main repository and should still reasonably ensure support of different PHP versions.

**Comment by mattab** [comment]
It's a nice idea, but we found that it's easier to keep all the jobs into one build as otherwise it gets complicated and time consuming to follow all the builds. 
Currently we run our builds on:

* UI tests on PHP 5.5
* all other tests on PHP 5.6 (both PDO MySql and Mysqli)

I reckon we only need to test the minimum version 5.5 and the maximum version ie. 7.2?
So maybe we could change to:

* UI tests on PHP 5.5
* `Alltests` suite (which runs Mysqli) on PHP 7.2
* Unit/integration/system (which runs on PDO) on PHP 5.6

or


* UI tests on PHP 5.5
* `Alltests` suite (which runs Mysqli) on PHP 5.5
* Unit/integration/system (which runs on PDO) on PHP 7.2

**Comment by Findus23** [comment]
Now that 7.2 has been released for a month, more and more people are trying to run Piwik with it.

I am using it for a few weeks without any apparent issues. (But SearchEngineKeywordsPerformance is broken because of `https://github.com/guzzle/guzzle/pull/1686` (fixed in guzzle 6.3))

But someone on the forum got an error message (once) while updating:
https://forum.piwik.org/t/count-parameter-must-be-an-array-or-an-object-that-implements-countable/26658?u=lukas

**Comment by sgiehl** [comment]
> I am using it for a few weeks without any apparent issues. (But SearchEngineKeywordsPerformance is broken because of https://github.com/guzzle/guzzle/pull/1686 (fixed in guzzle 6.3))

I'll check that and update dependencies for this plugin in the next release.

**Comment by Findus23** [comment]
The plugin seems to be working fine, but it's throwing warnings because of changes in PHP7.2

![grafik](https://user-images.githubusercontent.com/6266037/34271314-1657bb52-e68c-11e7-9d55-45c44530ab03.png)

**Comment by J0WI** [comment]
Up to now, test are not even run against PHP 7.1.
