### ISSUE TITLE
Invalidate archived reports/metrics

### ISSUE THREAD

**Issue by eramirezprotec** [matomo-org/matomo#12239]
Hi! I would like to know how Piwik decides to invalidate an archived metric/report. I'm having problems because I see some reports/metrics values one day (let's say yesterday), and the next day (today) everything changes several times. Looking at the logs, I found this: "Will invalidate archived reports for YYYY-MM-DD for following websites ids: XX,YY", and I can understand that Piwik needs to recalculate everything, but my question is how it decides which reports/metrics should be invalidated to get recalculated in the future? And why recalculating several times the next day?

Related https://github.com/piwik/piwik/issues/12251

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
