### ISSUE TITLE
Consecutive days with repeated data

### ISSUE THREAD

**Issue by eramirezprotec** [matomo-org/matomo#12240]
For two of my websites there is something weird happening:

1 - In the evolution graph (Visits over time) I can see the same number of Pageviews for two different days (2017-10-28, 2017-10-29). I already deleted the data in the archive_numeric_2017_10 and it was recalculated, but it shows again the same value (over one hundred thousand, so, it is practically impossible they can coincide).

2 - The Visit per server time report for yesterday (2017-10-30) is not complete, the data is being built according to the evolution of the actual day (today), and it is showing the same data than today. I deleted the blob record of the report (VisitTime_ServerTime) and ran core:archive. After all that, it keeps happening the same thing, it shows data for the actual hour, acting like if yesterday was today (today is 2017-10-31 and I'm talking about 2017-10-30). 

There was a change from summer time to winter time, both sites use Spain timezone. I believe that the hour adjustment caused the problem with Piwik logic.

Related https://github.com/piwik/piwik/issues/12251

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
