### ISSUE TITLE
Fix / Cleanup Tracker\TableLogAction::isActionTypeStoredUnsanitized()

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#12314]
While trying to resolve another issue, I spotted this piece of code.
Not sure if it is a bug or if it just can be removed, as the code can't be working since 2014:

```php
    /**
     * @param $actionType
     * @return bool
     */
    private static function isActionTypeStoredUnsanitized($actionType)
    {
        $actionsTypesStoredUnsanitized = array(
            $actionType == Action::TYPE_DOWNLOAD,
            $actionType == Action::TYPE_OUTLINK,
            $actionType == Action::TYPE_PAGE_URL,
            $actionType == Action::TYPE_CONTENT,
        );

        return in_array($actionType, $actionsTypesStoredUnsanitized);
    }
```

I don't think [this method](https://github.com/piwik/piwik/blob/3.x-dev/core/Tracker/TableLogAction.php#L268-L282) can return anything else than `false`. It's only used once, so maybe we can simply remove it.

**Comment by mattab** [comment]
@sgiehl It looks like this method is very buggy indeed. 
However if I read this correctly, it would still return `true` if and only `$actionType` is Action::TYPE_PAGE_URL ? (`$actionType == Action::TYPE_PAGE_URL` would be true, and in_array(1, array(true))` would return true.

**Comment by sgiehl** [comment]
seems we are both wrong. just tested that on command line. The method will always return `true` unless the value of $actionType is false (casted to boolean)

**Comment by diosmosis** [comment]
Started looking into this and thought it was a bug, but turns out it actually works as expected (in a very strange way). Here are two scenarios:

1) when `$actionType == Action::TYPE_DOWNLOAD`:

`$actionsTypesStoredUnsanitized` is set to:
```
array(
            true,
            false,
            false,
            false,
)
```

`in_array(true-ish, $actionsTypesStoredUnsanitized);` resolves to `true` as expected.

2) when `$actionType == Action::TYPE_EVENT_NAME`:

`$actionsTypesStoredUnsanitized` is set to:
```
array(
            false,
            false,
            false,
            false,
)
```

`in_array(true-ish, $actionsTypesStoredUnsanitized);` resolves to `false` as expected.

It's certainly weird code, but not broken. Will create a PR to make it less confusing.
