### ISSUE TITLE
Actions Report - Pages - incorrect data retrieved

### ISSUE THREAD

**Issue by Franc3sco** [matomo-org/matomo#12337]
Hello,

I am using the Pages report under the Action sections:

When i run the report for a particular page I have data showing when I select a specific range (see image below range is 27Nov 2017 - 3 Dec 2017)
![image](https://user-images.githubusercontent.com/14284002/33670284-fbc40496-daa4-11e7-8cbe-adcfb0228860.png)

If I run the report for the same page changing the period and selecting Year, so picking up 2017 I get no results (see image below)

![image](https://user-images.githubusercontent.com/14284002/33670247-ece46f38-daa4-11e7-8e43-9b6814995375.png)

What could be the issue here? Is it because of the archiving data process?

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
