### ISSUE TITLE
Allow Custom Dimensions of any size

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12348]
At the same time as we release Piwik 4.0.0, maybe we could also allow Custom Dimensions values of any size. See: https://github.com/piwik/plugin-CustomDimensions/issues/79

(since it will require a big schema update, we should do it as the same time as Piwik 4.0.0)

**Comment by tsteur** [comment]
Of any size is not specific. We could maybe set it to 500 or so. But this obviously limits how many custom dimensions there can be in total.

**Comment by mattab** [comment]
Duplicates https://github.com/matomo-org/matomo/issues/16150

**Comment by Webmasterei** [comment]
@tsteur as time moves on and data collections are getting bigger, I see a larger demand for this to be happening. 
I have a usecase now where we want to push all "ecommerce items" on a page/cart/checkout to a dimension but due to this restriction it's not possible. So a big +1 from my side to bring this into priorisation. [The Plans to do so are long-time announced.](https://matomo.org/faq/new-to-piwik/data-limits-in-matomo-no-limits/)

**Comment by tgruebel** [comment]
> @tsteur as time moves on and data collections are getting bigger, I see a larger demand for this to be happening. I have a usecase now where we want to push all "ecommerce items" on a page/cart/checkout to a dimension but due to this restriction it's not possible. So a big +1 from my side to bring this into priorisation. [The Plans to do so are long-time announced.](https://matomo.org/faq/new-to-piwik/data-limits-in-matomo-no-limits/)

I also think, this is an important feature, that should get priority.
