### ISSUE TITLE
GeoLite2 Deprecated Coordinates in 2019

### ISSUE THREAD

**Issue by m-cameron** [matomo-org/matomo#12411]
Maxmind has announced that they will remove coordinates from GeoLite2 in 2019.

https://dev.maxmind.com/geoip/geoip2/geolite2/

How can Piwik works without the coordinates? Must we subscribe to the commercial GeoIP2? Can we use IP2Location LITE DB5?

https://lite.ip2location.com/database/ip-country-region-city-latitude-longitude

**Comment by fdellwing** [comment]
Why you need coordinates? City should be precise enough for 99% of the users that don't use a commercial solution anyway.

**Comment by Findus23** [comment]
I'm not sure if Piwik uses the coordinates to display the cities on the map.

**Comment by fdellwing** [comment]
Well, the map works if you use other methods of geolocation instead of GeoLite DB. So there **should** be no problem with that?

**Comment by m-cameron** [comment]
Need to check the codes if latitude and longitude are being used. Any developers here?

**Comment by mattab** [comment]
As maxmind itself says "Latitude and Longitude are often near the center of population. These values are not precise and should not be used to identify a particular address or household."

from internal discussions: we do not really need lat/long values for each user but the lat/long are currently used for the following:
* Real time map: https://matomo.org/docs/real-time-visitor-world-map/
* Visitors map showing cities: https://matomo.org/docs/visitors-map/

One solution would be to have, in Matomo, a static mapping of cities -> lat,long and use this instead, so we know for sure lat/long are not more precise than the closest city. Then we could use this static mapping to fill in the lat/long info for each visit (even in the DB raw data) and keep our APIs and Maps working as before.

Whether to keep or delete the fields lat/long in the DB,  because the values can be set manually via the Tracking API, many people use and rely on this valuable info (and may have full consent to track locations), so we can keep the fields in the tables.

**Comment by oschwald** [comment]
MaxMind is no longer discontinuing coordinates in [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/):

> After careful consideration, taking into account customer feedback, we have decided against removing latitude and longitude coordinates from the GeoLite2 databases. We are in the process of reviewing coordinates used in all of our GeoLite2 and GeoIP databases to ensure there is no risk of misuse.

**Comment by mattab** [comment]
Thanks for letting us know @oschwald - closing this as won't fix then.
