### ISSUE TITLE
Fatal error: Cannot unset string offsets in JqplotDataGenerator

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12627]
Following error happened on `index.php?date=2018-03-18&viewDataTable=graphVerticalBar&module=VisitTime&action=getByDayOfWeek&widget=1&columns_to_display=nb_actions%2Cnb_uniq_visitors&idSite=1&period=week`

`"message":"Cannot unset string offsets","file":"plugins\/CoreVisualizations\/JqplotDataGenerator.php","line":106`

Haven't tried to reproduce myself so not sure if it is an easy fix or not.

**Comment by sgiehl** [comment]
Can be easily reproduces on demo: https://demo.matomo.org/index.php?date=2018-03-18&viewDataTable=graphVerticalBar&module=VisitTime&action=getByDayOfWeek&widget=1&columns_to_display=nb_actions,nb_uniq_visitors&idSite=7&period=week

But that might be by design. `columns_to_display` is handled as array, but a string is given in URL. Correct would be `columns_to_display[]=nb_actions&columns_to_display[]=nb_uniq_visitors` 

Need to investigate if we generate such broken urls anywhere in the code...

**Comment by mattab** [comment]
(It is also reproduced several times by customers)

**Comment by sgiehl** [comment]
Do you know a way to reproduce it in Matomo without calling the API directly (with incorrect params)
