### ISSUE TITLE
Personal Data Anonymisation & Removal tool for analytics raw data - GDPR compliance

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12641]
As part of our effort to build-in Privacy in our product and for upcoming GDPR compliance #12600 we would like to release a new privacy tool. 

* A raw data anonymisation tool where you will configure a date range, for example, "Remove Personal data fields for all Raw data older than 6 months"
* The tool would remove or full anonymise a few key attributes such as:
  * IP Address
  * ~Visitor ID~
  * ~Fingerprint config ID~
  * Location data including lat/long
  * One or several custom dimensions, and/or custom variables
  * User ID 

The new tool could be available in the existing Administration> Privacy. It would record a "Request to Remove personal data" which would be executed during the scheduled tasks.

**Comment by tsteur** [comment]
FYI: Unsetting eg all `idaction_event_category` values may result in many more pageviews to be reported because the Actions-Archiver basically says `where idaction_event_category is null and idaction_content_name is null => must be a page view`. So when such data is removed, it may really result in wrong reporting data or even weird action types that aren't maybe unexpected because suddenly behind `action.type` might be an ID 10 instead of an expected `1` for the page view.

**Comment by mattab** [comment]
The data anonymisation tool is now available under Administration > Privacy > Anonymise data > Anonymize previously tracked raw data.

This is fixed in #12558  along with other GDPR improvements.
