### ISSUE TITLE
Overlay API Calls: Many results for not existing page

### ISSUE THREAD

**Issue by TCahn** [matomo-org/matomo#12667]
Hi,
if you call "Overlay.getFollowingPages" for a not existing page, you get many strange results.

Example for a not existing page:
https://demo.matomo.org/index.php?module=API&method=Overlay.getFollowingPages&idSite=7&period=year&date=yesterday&format=xml&token_auth=anonymous&url=https://forum.matomo.org/noooooooooooooot-existing-page/

Could you please fix this bug. 
Thank you! :-)
Thomas

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
