### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [matomo-org/matomo#12888]
Hi. I'am graphic disigner. I want to contribute to this project, if you allowed I will send to you.

**Comment by sgiehl** [comment]
Sure. Feel free to send your proposals to hello@matomo.org
If you are keen on helping with other stuff like icons, fonts or anything else, let us know!

**Comment by Findus23** [comment]
Hi @mirzazulfan 

If you want to help with icons, there are a lot of places where design help can be useful.

Many of the icons in `plugins/Morpheus/images/` have been there since the beginning and really should be replaced with font icons, SVGs or at least high-res pngs.

Or it would be nice to have placeholder icons for non-detected browsers/os/brands/countries/etc. instead of the transparent png which we are using at the moment. 
see also https://github.com/matomo-org/matomo-icons/issues/11

Many thanks for any help.

**Comment by Findus23** [comment]
@mirzazulfan Did you have time to take a look at the designs?
Please reopen this issue or contact us per mail if you want to help.

**Comment by mirzazulfan** [comment]
Sorry for late reply, I don't know there is a notification.
![matomo](https://user-images.githubusercontent.com/36124339/46125818-06fc3200-c255-11e8-98c5-a6fc2e82260d.png)
