### ISSUE TITLE
More compact display of Contents impressions and Contents clicks in the Visitor Log

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12894]
When using Content Tracking, by design there will often be 5-10-15 different elements that became visible. Currently they are displayed each on their own line such as below screenshot.

![visitor log contents](https://user-images.githubusercontent.com/466765/39952418-74aaa0fc-55ea-11e8-9afb-31d02e1146be.png)

Maybe we can make the visitor log display more compact?

For example maybe we could combine all "content impressions" (respectively "content clicks") that have also the same content name. For example the following 4 content impressions:

```
* preview-liveaboard - MV Ocean Quest
* preview-liveaboard - Coral Sea Dreaming
* preview-liveaboard - MV Scubapro III
* preview-liveaboard - MV Scubapro II
```

and change it to:
`* preview-liveaboard -  MV Ocean Quest, Coral Sea Dreaming, MV Scubapro III, MV Scubapro II`.
* the tooltip could be the same as the MV Ocean Quest's tooltip (ie. we pick the first). 
* on click, it would expand and show the content impressions on 4 lines.

thoughts?

**Comment by tsteur** [comment]
You might additionally group together all content interactions that happened in a row and have them expandable as well when there eg more than 3 different content names which may be quite often the case as well eg 
![image](https://user-images.githubusercontent.com/273120/39971080-883354e2-5749-11e8-9089-5cf9544aeb7d.png)

**Comment by mattab** [comment]
see also https://github.com/matomo-org/matomo/issues/13136  Visitor log: Group all actions within a pageview together #13136

**Comment by tsteur** [comment]
@diosmosis What I meant is like when there are eg 2 content impressions following, show them normal. When there are eg 3 content impressions show them as:

* +/- 3 content impressions (on hover show title with summary)
  * ForceSSL - download
  * JsTrackerForce...
  * ...

if there was interacted with not sure... interactions be probably always good to show directly and shouldn't happen too often per page view.

otherwise could also say

* +/- 3 content impressions - 1 interaction (on hover show title with summary)
  * ForceSSL - download
  * JsTrackerForce...
  * ...

is that more clear?

**Comment by diosmosis** [comment]
@tsteur think that might be a bit redundant w/  #13136? W/ that there will be 3 levels of nesting + multiple expand/show links.

**Comment by tsteur** [comment]
Not sure, could work. As long as you can click again to make them disappear again (be useful when you want to get an overall overview again eg when there are many impressions)

**Comment by mattab** [comment]
Looking really good now! :+1: 

![Screenshot from 2019-06-29 23-00-54](https://user-images.githubusercontent.com/466765/60383178-d8e89e80-9ac1-11e9-8f29-c85cb4d0d746.png)
