### ISSUE TITLE
Plugins section not accessible

### ISSUE THREAD

**Issue by gtomasgard** [matomo-org/matomo#13043]
According to https://matomo.org/faq/plugins/#faq_21, there should be a "Marketplace" section in the 'Administration' section. I am a super user. Under "System" -> "General settings" I found a link to the plugins page, https://[my subdomain].innocraft.cloud/index.php?module=CorePluginsAdmin&action=plugins, but it returns the error 
![image](https://user-images.githubusercontent.com/19916339/41081458-2f49f6c0-6a2b-11e8-9271-31dc5593317a.png). Adding "&idSites=1" to the URL does not help.

**Comment by Findus23** [comment]
Hi,

This is the issue tracker for the Open Source software. 
The error message you are seeing is because installing custom plugins is disabled on InnoCraft Cloud. If you need another plugin, please contact the support [support (at) innocraft.cloud] and they will help you. (I think only official plugins are possible)
