### ISSUE TITLE
Improve config file and configuration overview in admin

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#13151]
We show an overview over all available and set configurations in Matomo administration.
Therefor the global.ini.php is parsed.
As we have a few config values that are completely commented out by default this view is a bit broken:

![image](https://user-images.githubusercontent.com/1579355/42439459-472da768-8363-11e8-914e-17d131358191.png)

![image](https://user-images.githubusercontent.com/1579355/42439508-6654c932-8363-11e8-8145-ea4bf415b76b.png)

Those lines also include config values that are completely commented out. 
Merging https://github.com/matomo-org/component-ini/pull/9 and updating the component might help a bit. But those value entries might be hidden completely afterwards.

Maybe we should provide a default value for ALL config values!?

@matomo-org/core-team  anyone any opinion on that?

**Comment by sgiehl** [comment]
with the component changes, config keys that are commented out wouldn't be displayed at all in most cases (if there are blank lines in between). Imho it would be the best solution to have default values for all config values. But afaik there's no possibility to set an empty array in INI.

**Comment by tsteur** [comment]
> with the component changes, config keys that are commented out wouldn't be displayed at all in most cases (if there are blank lines in between)

be good if they could still be displayed

The problem otherwise really is that some settings shouldn't be set by default like the proxy headers  or proxy ips maybe and especially `instance_id`. Also we can never really guarantee that a default value is set...
Just a random thought as there are not too many with no value... can we somehow whitelist them and then parse somehow the comments for eg `; $whitelistedConfig` and `;$whitelistedConfig` to detect them somehow? Haven't looked into it...

**Comment by Findus23** [comment]
In the meantime thanks to https://github.com/matomo-org/component-ini/pull/9 the comments are quite readable, but commented out options are still missing. (but to be fair, I think they would confuse more than help)

![grafik](https://user-images.githubusercontent.com/6266037/82754968-e6410280-9dd0-11ea-80e4-6d408267259d.png)
