### ISSUE TITLE
sql error the table piwik_log_hsr_event

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#13222]
[error] 5461#5461: *3467818 FastCGI sent in stderr: "PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'NaN' for column 'x' at row 1 In query: INSERT INTO piwik_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '122226',   1 => '10393',   2 => 1,   3 => '4402267',   4 => 'NaN',   5 => 'NaN',   6 => NULL, )" while reading response header from upstream

**Comment by tsteur** [comment]
Seems when there is a click on your website, the position of the click is not detected correctly. Could you please email shop@matomo.org with this problem and if possible, let us know on which website URL this happened and if possible even the browser? Just in case you know it, otherwise a link to your website may be enough too. We will follow up by email then.
