### ISSUE TITLE
It seems that the page generation time for angularjs application is not accurate, is there any other benchmarks for average generation in piwik?

### ISSUE THREAD

**Issue by maojunya** [matomo-org/matomo#13294]

**Comment by Findus23** [comment]
I am not entirely sure, what exactly the issue is here. As the page performance reports have been rewritten in Matomo 4 (https://github.com/matomo-org/matomo/pull/15736) this probably doesn't apply anymore.
If you are still experiencing an issue (in Matomo 4), please reopen this issue or create a new one with more details.
