### ISSUE TITLE
Tooltips appear all over the place but shouldn't

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13305]
We're now seeing  the black tooltip in Matomo over all form fields, and inline helps, etc. 

For example: 
![tooltip](https://user-images.githubusercontent.com/466765/44264167-15e0d500-a211-11e8-8d3d-0de27a7319b5.png)

Instead we do not want to see the tooltips on those fields and inline helps etc. Not sure when this was regressed but maybe in some recent Visitor profile/Visitor log improvements?

**Comment by sgiehl** [comment]
That's now automatically done for all elements having a title attribute. If no tooltip should be shown we imho should remove the title attribute.

**Comment by sgiehl** [comment]
Btw. guess that was added in https://github.com/matomo-org/matomo/pull/12800

**Comment by tsteur** [comment]
Not sure. Even when a title attribute makes sense, you wouldn't always want to see the tooltip directly. I think there's a reason you usually have to hover something for a while before a tooltip shows up for example. Just because it can be quite annoying to see all the time things popping up and tooltips immediately when you already know what it means etc.

I think it makes sense for some parts that tooltips appear immediately. Such as in the visitor log when hovering the country flag. But often enough the tooltip shouldn't appear immediately.

See eg this screen:
![aug-18-2018 09-25-24](https://user-images.githubusercontent.com/273120/44289517-b1814c80-a2c8-11e8-89c0-2c0291d9b63a.gif)

I reckon pretty much only the tooltip in the evolution graph on the line makes sense to appear immediately. All other ones should appear only after the regular browser delay. 

For some other elements we need to see if we can remove the title attribute 👍  Eg for the form fields. I think the `title` attribute is used to specify the title/label of the form element and therefore will be always set. So maybe for form elements we can ignore this kind of title attribute automatically everywhere?

Can we maybe define a class or something to indicate the tooltips that should show up immediately?

**Comment by mattab** [comment]
> I reckon pretty much only the tooltip in the evolution graph on the line makes sense to appear immediately. All other ones should appear only after the regular browser delay.

Sounds good that other ones appear after standard browser delay.

> So maybe for form elements we can ignore this kind of title attribute automatically everywhere

Makes sense :+1: 

>  It's rather annoying and there we should remove tooltip as in many other places.

Not sure if there are many such places, but this one example is definitely to be removed!
