### ISSUE TITLE
Piwik analytics not working

### ISSUE THREAD

**Issue by debrapearlman** [matomo-org/matomo#13410]
We had Piwik Analytics on our intrAnet site and it worked great.  We moved to an https:// format and changed the URL to school.kki.org from oldschool.kki.org.  When we did that, I started getting a 404 page, could not find the site.  Here is the code I used:

<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://intranet.kki.org/school/piwik/" : "http://intranet.kki.org/school/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 3);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://intranet.kki.org/school/piwik/piwik.php?idsite=3" style="border:0" alt="" /></p></noscript>

The site is on a WordPress Theme called Blocked by <der> 
What am I doing wrong?  
Thanks,

**Comment by fdellwing** [comment]
Thats what I call an oldschool tracking code. Did you tried using a new one provided by Matomo?

**Comment by tsteur** [comment]
I would suggest as well to go to Administration => Tracking Code and get the updated tracking code. Although I don't think your problem is tracking code related. It seems more of a problem with your server set up. 

Maybe try to log in to your Piwik/Matomo and see if you see if that works. If that doesn't work, there is for sure a server issue. If it shows any warnings, then you may need to configure the updated trusted host. If log in is successful and there is no warning, try updating the tracking code.

For further questions or if the problem persists I suggest you post the issue in our forum: https://forum.matomo.org/
