### ISSUE TITLE
Expand drop down menu list when searching for a site and make it so that you can see the full title.

### ISSUE THREAD

**Issue by davidaigle** [matomo-org/matomo#13706]
When we use the search drop-down menu to locate a site we want visitor data for, the drop-down doesn’t provide the full-name of the sites when searched it puts the beginning of the site and then mid-way it finishes it with “…”.  We have a pretty elaborate web presence, spread across multiple web environments on the Internet, Intranet and Extranet, in total we have over 200 websites or web-based applications or website sub-sections being tracked using Piwik. We were forced to use some common naming conventions for portions of the sites that belong to a certain group. When we use the drop-down search and search by site name, branch of the organization or title multiple results are filtered in and out and oftentimes if the beginning of the site name is the same for a number of assets we have to guess which one is the right one.

**Comment by katebutler** [comment]
There is a tooltip which shows the full name of the site on hover. Can you use this so that you don't have to guess which one is which?

**Comment by mattab** [comment]
Would it be possible to show more characters in the website selector from the current ~ 20 chars to maybe  up to 50 chars?  Ideally the site selector would stretch to up to 50 characters or so when there are website names this long in the list. Ideally it would automatically stretch and become wider if there are long sites and stay the current size otherwise.

(Hovering on tooltip is not really practical or user friendly as it takes many clicks and wait time)
