### ISSUE TITLE
Add user UI broken in IE11

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13826]
https://forum.matomo.org/t/problems-with-internet-explorer-11-ie-11/30903

If you add a new user in IE11, the UI is broken. As far as I was able to observe, there are at least two problems:

1. The `onfocus` and `onblur` events are missing or not working, they should add/remove the `active` class from the label.
2. The `:focus` pseudo-selector does not work, nothing is turned green.

![matomo12](https://user-images.githubusercontent.com/22813377/49801473-942a2f80-fd4a-11e8-9d2d-b0fbff55f9a4.png)

**Comment by tsteur** [comment]
We'll need to see if that's an easy fix or not. Do all other forms work well? Wondering if it is a materialize.css issue or an issue with our code.

**Comment by fdellwing** [comment]
I did not check other forms, just confirmed the message in forum on our test VM.

**Comment by tsteur** [comment]
I've debugged for quite a while and found out that the `disabled` attribute is causing it. Was at first thinking that it accidentally sets a `disabled` attribute on the input form, but the problem is actually the `disabled` attribute on the DIV element that defines the form component. When removing this attribute, everything works as expected.

![image](https://user-images.githubusercontent.com/273120/50254564-61bbb900-0453-11e9-8f09-cdb1f4fa15f7.png)

Calling `Materialize.updateTextFields()` fixes the issue, but would need to be called after every field change/keystroke/... so this is not a solution. 

Seeing there is eg this code:
![image](https://user-images.githubusercontent.com/273120/50254710-0b9b4580-0454-11e9-982b-782024475d6c.png)

Haven't debugged this further, couldn't really find a fix so far. Wonder if it is some IE or jquery bug.

Adding a placeholder attribute with an empty string kind of worked 

![image](https://user-images.githubusercontent.com/273120/50254842-7e0c2580-0454-11e9-813c-45085c0794e5.png)

and made the label appear correctly but the text was still shown like it is disabled...

![image](https://user-images.githubusercontent.com/273120/50254855-89f7e780-0454-11e9-8549-437c4f77d0eb.png)

for some reason this prefix for placeholder is applied for the color:
![image](https://user-images.githubusercontent.com/273120/50254911-bca1e000-0454-11e9-88dd-af4496d04184.png)

the only solution I can think of so far is to provide an alternative attribute and deprecate `disabled` in `field-directive.js`. Could use `matomo-disabled=...` or `disable=`. This worked for me as a workaround.

@fdellwing @diosmosis  any thoughts maybe?

**Comment by fdellwing** [comment]
I can confirm, that the `disabled` is causing the issue. If it is not a big deal, the easiest solution would be to refactor it to something different. To not break with HTML specs I would propose `data-disabled`.
