### ISSUE TITLE
Custom content in the footer

### ISSUE THREAD

**Issue by morpheus-87** [matomo-org/matomo#13870]
I would like to add custom links to the footer on the login page, how can I achieve this?

**Comment by tsteur** [comment]
You can configure a privacy and terms link see https://github.com/matomo-org/matomo/issues/12938. 
You could otherwise write a custom plugin potentially in case you are familiar with coding (PHP): https://developer.matomo.org/guides/getting-started-part-1

For all other questions please ask in our forum: https://forum.matomo.org
