### ISSUE TITLE
Remove GeoIP Legacy Implementation and switch users to Db-ip

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#13957]
Maxmind has completely discontinued GeoIP Legacy Lite support. No databases in that format are available for free download anymore. Commercial databases might still be up (don't have access, so can't check if that's the case)

See https://support.maxmind.com/geolite-legacy-discontinuation-notice/

Therefor we completely should remove the GeoIP Legacy support in one of the upcoming version or a least in 4.0.

The GeoIP Legacy Autoupdater should already be removed (or automatically be disabled if a GeoLite DB is configured) in one of the next releases as it can't work anymore.

**Comment by mattab** [comment]
Is the `core:archive` process failing for geoip1 users now that the DB downloads are discontinued? if so please assign to the next milestone.

**Comment by sgiehl** [comment]
if the task runs it fails:
```
ERROR [2019-01-14 10:54:40] 42709  /var/www/piwik_test/plugins/UserCountry/GeoIPAutoUpdater.php(167): GeoIPAutoUpdater: failed to unzip '/var/www/piwik_test/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.


Error: error or warning logs detected, exit 1
```

**Comment by mattab** [comment]
we'll probably stop using Maxmind soon, so closing this issue now, see #15308 - feel free to re-open if there is actually something we should do

**Comment by sgiehl** [comment]
We still need to remove the old GeoIP implementation and force users to switch to GeoIP2. It doesn't matter if the new GeoIP2 database will be from Maxmind or DB-IP
Note: The paid GeoIP (Legacy) databases from Maxmind are still available, but might be discontinued soon.

**Comment by mattab** [comment]
Assigning to Matomo 4.0.0 as it seems a good time for it, but feel free to move it out if not possible

**Comment by tsteur** [comment]
BTW be good if for users things happen automatically and they are switched over. 

Is there any issue if they were using Apache or other things to authenticate? As part of Matomo 4 we could otherwise also simply have a warning show up to super users they should be upgrading to GeoIP2 and then remove it as part of Matomo 5?

MaxMind DBs still work after signing up right? 
No preference though. Don't know if old DBs are still available. I suppose we can also migrate them now but then we should have a big warning as part of Matomo 3 mentioning they should upgrade to Geoip2. Mostly concerened about users that do geolocation server based and we maybe can't migrate them automatically. Might not be a big issue though. 

Nonetheless a warning as part of Matomo 3 be great.

**Comment by sgiehl** [comment]
Imho we can't simply switch them over. Downloading the new database and setting up the provider without any action doesn't sound right for me. I will add a warning in the admin for superusers that they need to configure a new geolocation provider, if GeoIP Legacy was used before...

People still using GeoIP Legacy will also have the "issue", that old data was stored with the FIPS region codes, whereas GeoIP2 will use ISO codes. So they need to run the console command to update them or the old data might not be displayed correctly everywhere...

And this only affects the old Geo IP implementation that was using Maxminds `*.dat` files. The Lite version is already no longer available. The paid databases are still available, but deprecated for a long while already. The new Maxmind databases `*.mmdb` will still work.
