### ISSUE TITLE
serverTimePretty 8 hours behind actual recorded time in Live.getLastVisitsDetails results

### ISSUE THREAD

**Issue by kkoch3** [matomo-org/matomo#13974]
In the Live.getLastVisitsDetails method of the Reporting API, I noticed that the serverPrettyTime field is off by 8 hours (behind the actual time). Attached is a json file with the results. In the file, the lastActionDateTime reflects the correct hour that is recorded in the Matomo database.

[serverPrettyTimeBug.log](https://github.com/matomo-org/matomo/files/2771369/serverPrettyTimeBug.log)

**Comment by mattab** [comment]
This is probably because this time is actually in the timezone in which your website is created, so this time is not in UTC. I'll close this but if you find a different behavior, feel free to re-open.

There still seems to be a bug somewhere since there is also this bug: https://github.com/matomo-org/matomo/issues/14504
