### ISSUE TITLE
Missing page calls on Behaviour/Pages

### ISSUE THREAD

**Issue by DominikFG** [matomo-org/matomo#14046]
We are using Matomo 3.8.0.
Now we have 2 problems that seem to be related.

1. We have pages that show neither when filtered for 01/2019 nor 12/2018 but for the week from 12/31/2018 to 01/06/2019 

![2018-12-31_2019-01-06](https://user-images.githubusercontent.com/11147963/51901586-4af47480-23b8-11e9-80c5-569ebf8d5572.JPG)
![2019-01](https://user-images.githubusercontent.com/11147963/51901591-4d56ce80-23b8-11e9-9ce3-e005363840b9.JPG)
![2018-12](https://user-images.githubusercontent.com/11147963/51901598-4f209200-23b8-11e9-8c0f-b0e622ce2e84.JPG)

2. When we open the transitions on that page we get another page that doesn't show in any of the previously filtered lists.

![transitions](https://user-images.githubusercontent.com/11147963/51901829-e2f25e00-23b8-11e9-8df0-7db81b59be09.JPG)

**Comment by tsteur** [comment]
Can you maybe check the visitor log or the day archive for 31-12-2018 whether the `Thailand_2` pageview was from there?

It's hard to say why they were missing. Are they under the same folder? Or maybe shown somewhere else? Are they shown when you don't search? I suppose you archive data through the CLI / cronjob? 

If you have many different page URLs (which could explain this issue), check out https://matomo.org/faq/how-to/faq_54/#faq_54 and maybe increase the limits. For example if you had heaps of different page URLs in December,  `Thailand_2` was possibly simply not included because it was not in top #5000  for example and it was grouped under `#other`. Same could be for `Thailand_3`.

You could try to increase those limits in your config file and then invalidate the data for December and January and archive them again which may fix the issue: https://matomo.org/faq/how-to/faq_155/
