### ISSUE TITLE
Add option to archive january archive of this / last year

### ISSUE THREAD

**Issue by garas** [matomo-org/matomo#14064]
I have set:
- _Delete old aggregated report data_ after 12 months
- _Keep all data for: Yearly+Monthly reports_
- MySQL has `innodb_file_per_table=ON`.

After Matomo deleted old data, but left yearly/monthly reports, table size for `piwik_archive_blob_2017_01` reported by phpMyAdmin reduced 150MB to 4MB. However actual `.ibd` size left 150MB.

After running `OPTIMIZE piwik_archive_blob_2017_01`, the `.ibd` file was rebuilt and now takes 4MB.

You can see data, index and free space by running 
```sql
SELECT `TABLE_SCHEMA`, `TABLE_NAME`, `DATA_LENGTH`, `INDEX_LENGTH`, `DATA_FREE`
FROM `information_schema`.`TABLES`
WHERE `TABLE_SCHEMA` = 'piwikdb' AND `TABLE_NAME` LIKE '%archive_blob%'
```

Could Matomo run `OPTIMIZE` on archive tables after deleting much data?

In my case it reduced Matomo total DB space 4GB to 1GB.

**Comment by garas** [comment]
I've tried that command. Options 'all', 'now', [hidden](https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CoreAdminHome/Commands/OptimizeArchiveTables.php#L78) `lastN` are not useful, I don't need re-optimize all or recent tables each month.

Last option is specify concrete months. But it is also hard generate month in shell script. But finally I found solution: `php console database:optimize-archive-tables 'now - 14 months'`. 13th month still has daily reports, 14th is the one I need, better keep not optimized data 1 month longer than forever.

However I still think Matomo could be run in this predictable (deleting daily, but keeping monthly or yearly reports) time when optimization is very useful. Maybe checkbox at  _Keep all data for_.

**Comment by tsteur** [comment]
I'm not sure if `optimize table` will work on all versions of MySQL 4.1+ (or 5.1+) with InnoDb (I know it's basically just rebuilding the table, but not sure what happens in older versions).

We could enable it for InnoDb for archive tables only. Log tables be too risky re downtime etc. Would for sure not enable it for log tables. In general, personally, I would disable `enable_sql_optimize_queries = 0` in config and only run the command regularly. Might be good to recommend this some day or make it default (you don't want to lock log tables)... @mattab 

Re the command:  I think in general `lastMonth`, and `first month of the year` (because it stores yearly archives there) be useful. When running this regularly, it should be a lot more efficient than optimizing all archives tables all over again.

So it would be definitely good to add an option for `first month of the year` (last month should be doable with `last1`).

**Comment by katebutler** [comment]
If the `dates` option doesn't match any of the predefined values ("all", "now" or the lastN options) then it is passed to the [DateFactory](https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CoreAdminHome/Commands/OptimizeArchiveTables.php#L94) - this means that "january" will already work.

There's no guide for the optimize tables command on matomo.org at the moment, so perhaps we should write some so that we can document this properly.

**Comment by mattab** [comment]
For now created a short new section in 
https://matomo.org/docs/managing-your-databases-size/#manually-optimizing-the-database-tables
![Screenshot from 2019-07-15 13-06-21](https://user-images.githubusercontent.com/466765/61191683-5edf2900-a701-11e9-932b-74afdaefc635.png)

What do you think is the next step for this issue @katebutler ?

**Comment by garas** [comment]
`php console core:purge-old-archive-data` already optimizes tables after purging.

But it just optimizes all dates independently if it was purged or not any data.
I should filter `$dates` to optimize only `if ($archivePurger->purgeArchivesWithPeriodRange($date) > 0)`).

https://github.com/matomo-org/matomo/blob/52f423008a761195b8316871d92131687b91f246/plugins/CoreAdminHome/Commands/PurgeOldArchiveData.php#L110-L124

**Comment by katebutler** [comment]
@mattab Thanks, I'll flesh out that doc a bit more and explain the options that are available, think that's all we need to do.

**Comment by mattab** [comment]
Do you maybe have an update on this one @katebutler?

**Comment by katebutler** [comment]
Suggested addition to the https://matomo.org/docs/managing-your-databases-size/#purging-and-optimizing-the-database-using-a-console-command section - I don't have WP access so @tsteur can you please add it?


To reduce execution time, you can select specific date periods to run these scripts for.  This means that you can target just the recent months, for which report data is likely to have changed.  Note that data for annual reports is stored in the archives for January of the appropriate year, so it is a good idea to optimize these regularly as well, e.g.

`./console database:optimize-archive-tables last2`
`./console database:optimize-archive-tables january`

**Comment by tsteur** [comment]
Cheers, done.
