### ISSUE TITLE
List of user agents to exclude could support regular expressions

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14186]
Currently it is not clear whether we support regular expressions for the setting "List of user agents to exclude".
In the list of IP addresses it says `Regular expressions such as /^sess.*|.*[dD]ate$/ are suported.`

Suggested:
* Check regular expression works when excluding user agents
* add `Regular expressions such as /^Good-example-of-regex-here$/ are supported.`
* rename `suported` to `supported` in the existing message (typo)

**Comment by sgiehl** [comment]
Note: Regular expressions are currently not supported for useragents. See https://github.com/matomo-org/matomo/blob/7b6a14626960795b0acdf4a064cd3982d7704f2b/core/Tracker/VisitExcluded.php#L342-L356

**Comment by simoncrowe** [comment]
Thanks for your reply @sgiehl. 

Is there any plan to add regular expression matching for "list of user agents to exclude" in the future, or should I assume that we (Ubiquity Press) will need to implement this feature ourselves?

**Comment by sgiehl** [comment]
@simoncrowe the issue is currently not planned within the next releases. If you would contribute the changes needed for that in a PR we would be happy to review and merge that. 
Alternatively if you would like to sponsor the development of that feature, feel free to get in touch with us: https://matomo.org/faq/new-to-piwik/faq_21953/
