### ISSUE TITLE
Need responsive Matomo opt-out iframe please

### ISSUE THREAD

**Issue by CDUCI** [matomo-org/matomo#14209]
In the bottom of the web page at www.ucicl.uci.edu the opt-out iframe is not responsive. 

I set the width at 1200px to look better.  It doesn't look great at 600px on any screen.  And it doesn't center the text.  Looks awkward.

Any suggestions please? Thank you!

**Comment by tsteur** [comment]
You could set the styles of the iframe to something like `<iframe .... style="... ;width: 100%;max-width:1200px;">`. 

If you wanted to center the text, there is a plugin that allows you to further customise it: https://plugins.matomo.org/CustomOptOut

**Comment by CDUCI** [comment]
Thank you for responding so quickly. Clarification please. We are using the Cloud version so it's not installed in our web server. Will this plugin work?

**Comment by tsteur** [comment]
It won't be available on the cloud. I suggest for any cloud related questions you get in touch with our support: support at matomo.cloud

I suggest you change the `<iframe style="border: 0; height: 100px; width: 1200px;"` to `<iframe style="border: 0;height: 120px;width: 100%;max-width:1200px;"` and I noticed you also need to update the element above from `<div class="row">` to `<div class="col-12">` otherwise it cannot get the full width. You nested before a row within a row instead of making it a column.

should look like this:
![image](https://user-images.githubusercontent.com/273120/54572287-97207480-4a4b-11e9-8706-12a88d23ed53.png)

and then you maybe don't need to center the text.

**Comment by CDUCI** [comment]
Thank you so much!!  I made the 2 changes (iframe and col-12) as you suggested and the responsiveness is perfect.  Very much appreciated.
