### ISSUE TITLE
Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() 

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14250]
Sadly this error got not fixed with #14236. So if someone updates from 3.8.1 to 3.9.1 he still gets the error.

There is already one forum post about it: https://forum.matomo.org/t/update-from-v3-8-1-to-v3-9-1-failed/32215
I also noticed the problem on my second Matomo instance.

//cc @diosmosis

**Comment by Talkless** [comment]
Just got this error while upgrading to 3.9.1:
```
Matomo encountered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')
```

**Comment by Sh4d0wF1gh7** [comment]
Got also on two instances this error...
After returning back all seems to work but I think the update is not complete?

**Comment by guytarr** [comment]
After upgrade to 3.9.0 and another upgrade to 3.9.1 UI show 3.9.1 but in database, core still in 3.8.1, and plugins like version_MediaAnalytics still in 3.3.1.

The archive job won't run because they are missing table :

> Table 'matomo.matomo_log_media_plays' doesn't exist - in plugin MediaAnalytics

The ./console core:update didn't return anything

I've this php errors
PHP Fatal error: Class 'Piwik\Plugin' not found in [...]/htdocs/plugins/Installation/Installation.php on line 23



After adding
in Installation/Installation.php
`use Piwik\Plugin;`

It's ok 
./console core:update work and everything seem fine (value core and plugins version up to the good file version of 3.9.1 release in database matomo_option)

**Comment by MackieeE** [comment]
Much like Sh4d0wF1gh7, it was fine after returning to the same install script. It was marked as "already updated".

Unsure if actually complete however.

**Comment by larsen0815** [comment]
We are still on 3.8.1 because of this problem. Is there an expected date when this will be fixed?

**Comment by Findus23** [comment]
@larsen0815 This bug has already been fixed with 3.9.1, but as during the update the old code (with the bug) is running, you will still see the error when upgrading to 3.9.1. But the next upgrade from 3.9.1 should then be fine.
See here: https://github.com/matomo-org/matomo/issues/14227#issuecomment-475303119

**Comment by fdellwing** [comment]
You can simply do a manual three step upgrade (https://matomo.org/docs/update/#the-manual-three-step-update) to avoid the problem. The error is part of the one click updater.

**Comment by larsen0815** [comment]
Ah ok. I was already using that workflow. Upgraded my dev system and got no errors that way.

**Comment by metalocator** [comment]
Got this error using the 1 click updater from 3.8.1 to 3.12.0.
