### ISSUE TITLE
Old reports start missing after some time

### ISSUE THREAD

**Issue by L3on1d** [matomo-org/matomo#14271]
Hi!

Our current matomo version: 3.9.1

Since version 3.9.0 I noticed that some reports start missing after some time. For example we had normal reports for Friday March 22 and Saturday March 23, today I noticed that these reports was missed from our system, no data at all. Screenshot attached.
![report](https://user-images.githubusercontent.com/11537656/54996391-d57cdd00-4fd1-11e9-8417-c37dfd50c449.JPG)

Another problem, I can't re-process these reports due our "Delete old visitor logs and reports" settings, we keep raw data for 2 days only.

Any thoughts how to bring these reports back? 

No errors in matomo logs.

**Comment by toredash** [comment]
If you don't have access to raw data, then there is no way to get that data back, AFAIK.

**Comment by L3on1d** [comment]
Question why this report was missed from system, yesterday I was able to read data from it, today I see blank page.

**Comment by tsteur** [comment]
If you still have the log files on the webserver, you can use log analytics to replay the traffic see https://github.com/matomo-org/matomo-log-analytics There should be a parameter like `replay-tracking` or so which will replay all tracking requests to piwik.php/matomo.php and you can also define a start/end date time optionally etc

Otherwise might be similar to https://github.com/matomo-org/matomo/issues/14271
