### ISSUE TITLE
Error while trying to connect to the database server: Server sent charset unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by JeyakumarThangaraj** [matomo-org/matomo#14299]
Dear Team,

I am getting below error while do database setup.
"Error while trying to connect to the database server: Server sent charset unknown to the client. Please, report to the developers".  We cant change utf8mp4 charset to utf8 in MySql server since it is used by some other application. Kindly advise what else we can do to fix this issue. 

Php Version : 5.5.38
CentOS 7

![image](https://user-images.githubusercontent.com/49137580/55306477-17d46d00-545d-11e9-9286-5f7ff42e3c8c.png)

Thanks & Regards,
JK

**Comment by Findus23** [comment]
Hi,

I think you can change MySQL charsets per database or even per table, so as long as your server supports both, you should be fine.

**Comment by JeyakumarThangaraj** [comment]
Hi Findus,

Getting same error even after changing default charset to utf8. Kindly advise

![image](https://user-images.githubusercontent.com/49137580/55405511-e47c0600-5562-11e9-8591-c07fd5e0dcf1.png)

**Comment by JeyakumarThangaraj** [comment]
Dear Team,

Kindly advise.

**Comment by Findus23** [comment]
@JeyakumarThangaraj 
Have you taken a look how you can make the client (so your PHP setup) accept the charset?

e.g. try out https://stackoverflow.com/a/43442839/4398037

**Comment by tsteur** [comment]
@Findus23 @JeyakumarThangaraj  does it maybe make sense to continue this conversation in the forums? More people might have an eye on this question there and we're trying to keep the issue tracker clean from questions etc as it's otherwise not possible to manage all the issues. Or we could close the issue and you continue discussing it here? We can also keep it open but I doubt it is an issue in Matomo.
