### ISSUE TITLE
Composer-izing libs/

### ISSUE THREAD

**Issue by szepeviktor** [matomo-org/matomo#14291]
Are there plans to clean up libs/* and use modern composer packages instead?

**Comment by fdellwing** [comment]
Matomo already uses composer.

**Comment by szepeviktor** [comment]
Thanks.

Are there plans to remove all libs and use **only** composer packages?

**Comment by fdellwing** [comment]
Yes: https://github.com/matomo-org/matomo/pull/14082

**Comment by tsteur** [comment]
> Are there plans to remove all libs and use only composer packages?

Are there any particular reasons why?

**Comment by szepeviktor** [comment]
I've started analyzing Matomo with PHPStan in #14290 and those libs are old and poorly written code, had to exclude all of them.

**Comment by tsteur** [comment]
Will close the issue. We're not going to update / change any libraries unless we have new feature requirements that require a new library if requirements can't be met by a current lib or unless they have security issues or so. We don't just update libs though just because of poorly written code or because they are old (old doesn't mean bad) when things work in general. If you find a lib that has a minor version update (same major version) and is available in NPM feel free to issue a PR and we will review over time.

Cheers
