### ISSUE TITLE
Restrict open-ended require to the major Matomo version it defined

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14342]
I just noticed that my Matomo instance had the `IPv6Usage` plugin running.

The plugin doesn't officially support Matomo 3, [hasn't been adopted by anyone](https://forum.matomo.org/t/adopt-a-plugin/26869) and [removed from plugins.matomo.org](https://plugins.matomo.org/IPv6Usage) 

```json
    "require": {
        "piwik": ">=2.12.0"
    }
}
```

But as the plugin has an open-ended `require` it hasn't been deactivated by Matomo.

I think Matomo should at least show a warning to superusers as subtle bugs may be caused by them and maybe this way more people would try to adopt popular plugins that aren't maintained anymore.

**Comment by tsteur** [comment]
We probably can't really do this since we don't know if the plugin is still maintained or not, whether it has been installed through the marketplace or receives updates from somewhere else etc unless we assume in Matomo as well that the plugin isn't compatible with Matomo 3.X. But then it could still for a while receive updates for Matomo 2.X version etc unless we have removed it from Matomo Marketplace. This would assume though that Matomo knows "this plugin is a plugin from the marketplace" which can be hard. Eg when the plugin has been removed from the Marketplace, then Matomo cannot know it. Or someone might develop their own plugin having by accident same name as a marketplace plugin etc.  I doubt we will implement any of this any time soon (or ever).

I guess the only thing we could do at some point is to assume a `"piwik": ">=2.12.0"` is not compatible with 3.X and therefore deactivate the plugin. So it has same logic as marketplace.

**Comment by Findus23** [comment]
> I guess the only thing we could do at some point is to assume a "piwik": ">=2.12.0" is not compatible with 3.X and therefore deactivate the plugin.

That's what I meant with this issue, it was just too long for the title :)

But I would also suggest showing a message as it would be confusing otherwise why the plugin is gone.

**Comment by Findus23** [comment]
It would be great if with Matomo 4 we could make the breaking change to mark all `>=2.x.x` plugins as incompatible.

**Comment by tsteur** [comment]
btw just had a quick look around https://github.com/matomo-org/matomo/blob/3.13.3/core/Plugin/Dependency.php#L100 as I thought we're already doing that but maybe we don't and only do it on the marketplace so far. Might have not looked in the right place.
