### ISSUE TITLE
 Galaxy S9 shows as duplicate in reports (the ending %2B is not correctly displayed)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14564]
Reported by email: 

>  I have multiple entries for the GALAXY S9.

See screenshot:

![Screenshot from 2019-05-24 18-30-10](https://user-images.githubusercontent.com/466765/58307180-0ce0fc00-7e52-11e9-9dfa-c077ecaf5e84.png)

In the UI it looks like this:

![Screenshot from 2019-05-24 18-31-54](https://user-images.githubusercontent.com/466765/58307248-3a2daa00-7e52-11e9-80ea-b0e59f80c807.png)

Likely an encoding issue where the ending `%2B` is not displayed correctly in the reports?

**Comment by sgiehl** [comment]
I have investigated the issue. The data is correctly tracked and also correctly included in the resulting datatable returned by the API method. The problem is a result of the `SafeDecodeLabel` filter that is applied to in the `DataTablePostProcessor`, which does a `urldecode` on all lables. As the device name includes a `+`, it's converted to a ` `.

@mattab @tsteur @diosmosis  does anyone have a good idea how to tackle that? Removing the `SafeDecodeLabel` might have various side effects. Also there might be labels containing a `+` that should be converted to a space :man_shrugging:

**Comment by diosmosis** [comment]
This is a similar problem I tried to solve here: https://github.com/matomo-org/matomo/pull/13481

Every change I made resulted in a new broken test, haven't worked on it in a while.

**Comment by mattab** [comment]
As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
