### ISSUE TITLE
API: hideColumn doesn't remove group and main_url in MultiSite method

### ISSUE THREAD

**Issue by viktorix** [matomo-org/matomo#14597]
This seems to be a bug. I can't hide group and main_url columns. If I use `hideColumns=label,group,main_url` it will hide label, but group and main_url remain.

I tried different combinations, group alone, main_url alone, etc. The result is always the same, group and main_url are not hidden.

**Comment by sgiehl** [comment]
It's actually kind of expected behaviour for the current implementation. `group` and `main_url` are no real columns, but metadata. using `&hideColumns=label&disable_queued_filters=1` would hide them, as it disables the metadata processor. 

Nevertheless it might be expected behaviour that `hideColumns` would also hide metadata. ping @mattab

**Comment by tsteur** [comment]
AFAIK it shouldn't. It would need a new parameter `hideMetadata` or something maybe.

**Comment by viktorix** [comment]
Thanks @sgiehl. Using `disable_queued_filters=1` works well in this case.
