### ISSUE TITLE
Tracking code fails on Microsoft Edge

### ISSUE THREAD

**Issue by wvdvegt** [matomo-org/matomo#14614]
I've updated my website with the tracking code suggested by Matomo 3.10.0.

It works for Chrome (i see the real-time logging change) and for the Edge beta which uses the Chrome engine. 

However using Edge it totally fails to generate any logging. Using Fiddler i see Edge retrieving a age 'matomo.php?action_name=  etc.) and get a 1x1 pixel returned. So it should be working yet the hit do not show up in Matomo.

**Comment by Findus23** [comment]
Can you make sure you don't have DoNotTrack enabled?

You could also enable https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker which makes the request return a verbose log instead of the pixel.

In general [the forum](https://forum.matomo.org/) is more useful for general troubleshooting and we try to limit the issue tracker to confirmed bugs that can be reproduced.

**Comment by wvdvegt** [comment]
Thx, indeed a donottrack header. 

Nice debugging feature btw
