### ISSUE TITLE
Bug: Website Measurable URLs unexpected behavior

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#14615]
# Summary

During the configuration of the website measurable, you have to specify one or several URLs.

## Current behavior

If I specify an URL like `https://mysite.com`, everything is ok.

But, if I use an URL like `//mysite.com` to avoid specify `https://` or `http://`:

* from `All Websites` page, **Visits** and **pageviews** keep working and increment values
* No Widgets from the Dashboard display new values (ex: real time count still at 0)
* When I come back to the configuration, the URL become `////mysite.com`

### First scenario

Display an error message if the URL is not valid (URL validator)

### Second scenario

Allow to use URLs that begin by `//` (without `https` or `http`) and support them into data incrementation.

**Comment by tsteur** [comment]
Cheers for the report, we'll only prepend `http:` instead of `https://` in the future: https://github.com/matomo-org/matomo/pull/14616

Specifying `//foo.com` is not supported unfortunately. You could instead configure multiple urls with `http://...` and `https://`. In https://github.com/matomo-org/matomo/blob/3.10.0/plugins/WebsiteMeasurable/Settings/Urls.php#L89 we are checking the URL looks valid but it was not requiring a scheme.
