### ISSUE TITLE
Upgrade to 3.10 causes all access to fail

### ISSUE THREAD

**Issue by nboscia** [matomo-org/matomo#14645]
After upgrading to 3.10.0, both instances of Matomo are failing to log people in.  After a dozen attempts and doing "Remember Me", I can sometimes get it to work for a single page.   I confirmed directly inside the databases that users are still there with proper permissions and even admin is still set to super-user.  I get errors that whomever I login as, does not have "View" permission for whatever page/site I'm loading, regardless of super-admin status or "View" set to access.  

My gut is telling me this is a SiteMinder Issue, which we use a CA web agent inside Apache to do authentication for the admin access.  I never had to configure proxy stuff inside Matomo before since we're not proxying any data through it, just doing an initial login.   Do specific headers need to be passed through login? It seems like a cookie is not getting set.  There are a lot of these errors in the Apache logs:

 Error in Matomo: Zend_Session is currently marked as read-only.

**Comment by tsteur** [comment]
Seems like a server configuration issue which may be better discussed in the forums: https://forum.matomo.org @nboscia 

We don't know your exact server set up here so we can't be much of help unfortunately. Could you maybe post in the forums or check out our support plans https://matomo.org/support-plans/ ?

If you could otherwise investigate a bit more and have some hints for us what is happening, we can maybe work on a fix for it.
