### ISSUE TITLE
Load Pages Row Evolution out of memory after upgrade to 3.10.0

### ISSUE THREAD

**Issue by xpader** [matomo-org/matomo#14667]
After upgrade to 3.10.0，I have two problem:
1. Open Pages Row Evolution out of memory.

Response:
Matomo encountered an error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 147456 bytes) (which lead to: Allowed memory size of 268435456 bytes exhausted (tried to allocate 147456 bytes))

My php.ini set memory limit to 512M, and my website's uv and pv just about 8000 and 100000 for daily.

2. Open Events Row Evolution show Error:

Error: The parameter 'secondaryDimension' isn't set in the Request, and a default value wasn't provided.

**Comment by tsteur** [comment]
> Error: The parameter 'secondaryDimension' isn't set in the Request, and a default value wasn't provided.

I've fixed this issue 5 minutes ago in https://github.com/matomo-org/matomo/pull/14666

The other issue I recommend increasing your memory and / or to ensure you have browser archiving disabled see https://matomo.org/docs/setup-auto-archiving/
BTW: The size of the memory would not really depend on the amount of traffic you have with row evolution since it's only handling aggregated data. The traffic would only matter if you have eg browser archiving enabled.

**Comment by xpader** [comment]
My browser archive is closed, and archive was set in crontab.

**Comment by tsteur** [comment]
Thanks for letting us know. The 512MB memory might help. As said, the memory usage doesn't depend on the traffic size here unfortunately.

**Comment by xpader** [comment]
Yes, But the memory used was too big, I think there is room for improvement here.
