### ISSUE TITLE
GeoLite2 database will never be updated

### ISSUE THREAD

**Issue by michel-kraemer** [matomo-org/matomo#14705]
AFAIK, the URL to the GeoLice2-City database is:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

If I enter this in my settings and then run `php /var/www/matomo/console scheduled-tasks:run --force`, I get the following error:

```
GeoLite databases have been discontinued. Skipping download of https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz. Consider switching to GeoIP 2.
```

I think the problem is in this file:
https://github.com/matomo-org/matomo/blob/master/plugins/UserCountry/GeoIPAutoUpdater.php#L144-L147

The code only checks for `GeoLite` but not `GeoLite2`. As a consequence, the database will never be updated.

Is my observation correct or do I miss something?

**Comment by sgiehl** [comment]
It seems you configured the GeoIP2 database for GeoIP (Legacy), which can't work. You may need to enable the geoip2 plugin if it is not already active. You should then be able to configure GeoIp2 instead of GeoIp (Legacy).
If GeoIp2 plugin is not installed/available you may need to update Matomo first...

**Comment by michel-kraemer** [comment]
Ah! I didn't know the plugin was inactive. Thanks a lot!
