### ISSUE TITLE
embed dashboard iframe auto-height 

### ISSUE THREAD

**Issue by skerbis** [matomo-org/matomo#14716]
is this possible? 
Is there a way to do this?

**Comment by tsteur** [comment]
@skerbis not sure what you mean? Can you describe this in more details?

**Comment by skerbis** [comment]
Hi,sure: 

i embed the dashboard by using the code like this: 

```html
        <iframe src="https://domain.tld/piwik/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=7&period=week&date=yesterday&token_auth=00000000000000
" frameborder="0" marginheight="0" marginwidth="0" width="100%" style="height: 100vh"></iframe>
```

Is there a Way (a JS-Code) to auto resize the embedded iframe so that it fits to the body of it?
I would like avoid scrollbars.

**Comment by tsteur** [comment]
We have the iframe-resizer embedded in Matomo and AFIAK load it on every request.  You could try if it just works

**Comment by skerbis** [comment]
do you have an example code

`  iFrameResize({ log: true }, '#matomoframe')` 

does not work. 
I've installed the frame-resizer and gave the iframe the id #matomoframe

**Comment by tsteur** [comment]
Sorry I don't really have the time to investigate much here right now.  I can see though that `iFrameResize` is being loaded in the widgetized iframe if you use the latest Matomo version.
Do you get any error? Is it on the same domain or so?

**Comment by skerbis** [comment]
I will invastigate it tomorrow. Thx

**Comment by skerbis** [comment]
I get the following Error: [iFrameSizer][Host page: ng-app] – "IFrame has not responded within 5 seconds. Check **iFrameResizer.contentWindow.js** has been loaded in iFrame. This message can be ignored I…"

**Comment by tsteur** [comment]
Just tested it. I didn't get an error but noticed it isn't working because the widget that you embed would also need to load https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js

Then it works... Did you maybe want to create a PR? We could place the file in this directory where we already have the other iframeResize file: https://github.com/matomo-org/matomo/tree/3.x-dev/plugins/CoreHome/javascripts

and we would load the file here: https://github.com/matomo-org/matomo/blob/3.12.0-b1/plugins/CoreHome/CoreHome.php#L305

**Comment by skerbis** [comment]
Thanks ... PR will come :-)

**Comment by skerbis** [comment]
Thanks Thomas @tsteur ;-)
