### ISSUE TITLE
Afther upgrade to 3.11.0 getting "Oops… there was a problem during the request." in Vistor Profile and Visits Log  

### ISSUE THREAD

**Issue by Eckybrazzz** [matomo-org/matomo#14713]
Hi there,

I have this issue some time now and had no time to report it before. I got annoying and start searching for a clue and found several same issues here. As this is another version I opened a new Issue.

Issue 1 open the Visits Log gives

> Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance. 

Issue 2 open the Loading Visitor profile...
> It hangs and won't show any data

```
Matomo version: 3.11.0
MySQL version: 10.3.16-MariaDB
PHP version: 7.3.7 
```
I have some warning, but they never gave any problems in the past
```
System Check
Warnings
-   Database abilities
-   Geolocation
```

**Comment by tsteur** [comment]
@Eckybrazzz It might be likely a memory issue. Check if you can access any webserver or PHP logs this might give you more information. You could also try to increase memory and see if it still happens. Otherwise be good to ask a question in https://forum.matomo.org
without any information from the logs we can't do anything unfortunately.
