### ISSUE TITLE
Avoiding 7 days limitation of ITP 2.1 for 1st party cookies to identify returing users

### ISSUE THREAD

**Issue by Martin-Simon** [matomo-org/matomo#14819]
How can I avoid the 7 days limitation of ITP 2.1 for 1st party cookies to identify returing users even after 7 days with Matomo?

**Comment by tsteur** [comment]
Hi @Martin-Simon could you please ask your question in our forum https://forum.matomo.org ?

Thanks

**Comment by mattab** [comment]
extract from a private conversation about ITP and Safari and Consent and first party cookies 7 days limitation:


· All cookies are limited to 7 days - this also includes the mtm_consent cookie, please see image below. 1st visit date 20th of March and all pk_ cookies are set to expire 27th of March.

· Unique visitorID count per userID is much higher for Safari than for the other browser which also indicates that cookies are being cleared more frequently here ( Numbers below are from 1st of February)



**> How can we modify this in matomo - so that tracking cookies (all except for mtm_consent) are set to expire in 7 days for all browsers?**

You can call setVisitorCookieTimeout to 7 days, this should do the trick it seems.

**> How would we handle the mtm_consent cookie? As we of course do not want to keep asking for consent when it already was given 7 days ago.**
**>- We can of course set up a JS function which would keep renewing the consent cookie if it exists - but perhaps you guys have a better solution for this**

That's probably the only way currently :-| . However, this would work only if a user visits again before the 7 days. You would just need to ask for consent again otherwise...

I wonder if Safari/ITP offers some solution for this issue. But in general it's our understanding that you have to ask again for consent after 7 days if they haven't visited yet.
