### ISSUE TITLE
Matomo behind a reverse proxy https --> http - issue with login page

### ISSUE THREAD

**Issue by comp-lsa** [matomo-org/matomo#14878]
Hello,
We are using Matomo (version 3.9.1) behind a reverse proxy https --> http.
The reverse proxy is not managed by us but it seems to be configured correctly.
We have an issue with the login page. We use the reverse proxy mapping address and after entering the login & password we have the error “can’t reach this page” because it tries to go in https to our backend server. Simply making “back” redirects us to the https address of the reverse proxy and we are connected, we can then work normally … Matomo works, visits are tracked, we have access to the administration … but we would like to get rid of this issue …
We have configured matomo according to the article: How do I configure Piwik when the server is installed behind a proxy? FAQ - Analytics Platform - Matomo
The reverse proxy administrators ensure us they have correctly setup the mapping and redirections from https to http, and they assume somewhere in matomo the server address with https is hardcoded for the login actions.
Could you please advice on this issue ?
Thanks in advance.

**Comment by tsteur** [comment]
Maybe check what URL is configured in `matomo_option` table where `option_name` is `piwikUrl` and adjust it if needed. Make sure your trusted hosts in the `config/config.ini.php` is correct too. 

Otherwise we can't really do much since it could be many different things including the proxy being not correctly configured. I'll close the issue therefore but if you identify any clear bug where the environment is 100% correctly set up and you can find the problem then we're happy to apply a patch or so.
