### ISSUE TITLE
Multi tenancy architecture

### ISSUE THREAD

**Issue by brunowego** [matomo-org/matomo#15073]
I'm working for Banco do Brasil, and here we have billions of access every month. We decide separate each product to collect in a dedicated Matomo.

After months working with Matomo (piwik), I really appreciate the platform and I love the architecture that this are builded.

So, already passed through the thought of separating each site into a separate database as a multi-tenant architecture? That makes sense? Thanks.

**Comment by mattab** [comment]
Hi @brunowego, we usually recommend that one Matomo instance tracks  500M pageviews or 1 billion actions per month. We haven't (yet) had opportunity to test on more than 500m-1billion range. Most features actually work well. Above 500m/1billion it is usually recommended to add all other sites to a separate new Matomo instance (or multiple). Because it's easy to create a new instance (there is an un-documented system using named config files), we're not planning multi-tenant architecture, but may do it later (probably a UI to connect all the different Matomo servers, and make it easy to view sites/users across instances) 

How many pageviews and total actions are you currently tracking per month in your Matomo? and how many do you track more in the next 12 months?

**Comment by mattab** [comment]
Any update @brunowego on your multi tenancy tests? happy to help, feel free to contact us at matomo.org/contact/

**Comment by brunowego** [comment]
Hi @mattab, sorry for the delay. So, for this moment we decide for other alternative. We are a small team. I will close this, in future we open again. Thanks!
