### ISSUE TITLE
Segments not filtering correctly

### ISSUE THREAD

**Issue by TheFirstGoodmaN** [matomo-org/matomo#15163]
I got notified about an issue and could reproduced it with different installations of matomo 3.12.0

### Downloads
* select a website
* go to Behaviour -> Downloads
* create a new segment
* select `Download URL is` a complete URL and apply
In my opinion there should only be one entry with this full URL and nothing else.
* in my example `https://some-domain.tld/saas/_images/outlook_configuration.png`
![downloads-all](https://user-images.githubusercontent.com/1267672/68945789-7b739680-07b1-11ea-89bd-f47be609894e.png)
![Downloads-segment](https://user-images.githubusercontent.com/1267672/68945792-7c0c2d00-07b1-11ea-8d66-bd6de7ae24c0.png)
![downloads-segment-applied](https://user-images.githubusercontent.com/1267672/68945790-7b739680-07b1-11ea-8fcf-f5d98cc7bac4.png)

### Pages
* select a website
* go to Behaviour -> Pages
* create a new segment
* select `Action URL contains` enter a par of an existing URL in my example `saas`
* the same result if i use `Page URL` instead
* the first entry is correct but in the rest i cant find any sign of `saas` in the URL's
![pages-all](https://user-images.githubusercontent.com/1267672/68945781-7adb0000-07b1-11ea-8f46-fa72b8d585e2.png)
![pages-action-url](https://user-images.githubusercontent.com/1267672/68945777-7a426980-07b1-11ea-879d-a542111d54fa.png)
![action-url-result](https://user-images.githubusercontent.com/1267672/68945784-7adb0000-07b1-11ea-8a46-074ed3553965.png)
![page-page-url-segment](https://user-images.githubusercontent.com/1267672/68945788-7b739680-07b1-11ea-9a7d-fa95bf3f3fbd.png)
![page-url-result](https://user-images.githubusercontent.com/1267672/68945786-7b739680-07b1-11ea-883a-6ba6b776d1af.png)

Maybe am i missing something completely but it seems wrong for me.

**Comment by fe-hicking** [comment]
Related:

https://forum.matomo.org/t/filter-page-urls-by-segments/34859

To is this is a critical bug. One of the main tasks in Matomo is no longer working as we and clients expect it. This should not have been implemented in a non-breaking minor release.

It needs to be made an optional segment option. Until it becomes optional in 4.0.x it should be reverted in a new regression release of 3.x.

**Comment by fe-hicking** [comment]
Related: https://github.com/matomo-org/matomo/issues/15133

IMO this issue is important.

**Comment by tsteur** [comment]
See https://github.com/matomo-org/matomo/issues/15130#issuecomment-551252343 on how to restore old behaviour. We're not planning to restore the previous behaviour as default behaviour unfortunately. Segment feature is supposed to work like it is implemented now and it was buggy how it worked before. We totally understand this is frustrating but there's no way we can make everyone happy unfortunately and we followed to what most users are wanting/expecting and how it works on other analytics solutions. The feature you're referring to be a "filter" which we don't have yet. [Custom Reports](https://plugins.matomo.org/CustomReports) supports it though.

**Comment by PeteTrombone** [comment]
Why is this issue closed? There is still no solution for many matomo users.
Our company have the same problem like TheFirstGoodmaN and fe-hicking. Custom Reports, Custom Dimensions don't bring the same result an to disable the new behaviour is no solution for us.

Like the example of TheFirstGoodmaN, there is no difference between page-url and action-url anymore.
As far as I know the "bug" referred only to the parameter "Page-URL", why was the function also changed for the parameter "Action-URL"?

In addition, we now even have a big data protection problem, because more data is displayed as desired/allowed. In our case, we are no longer compliant with gdpr and we can not use this anymore.

**Comment by tsteur** [comment]
@PeteTrombone just to understand why do you not want to disable this feature to have old behaviour? In general we can't have the same feature working in two different ways and everyone would expect to behave it one or the other way. We're really talking of one feature here. Be keen to hear your thoughts on why Custom Reports did not do the trick here and what we can maybe improve. Feel free to get in touch with our support about that: shop at innocraft.com

**Comment by viezel** [comment]
@tsteur just looping back here. I have another scenario using Events API where it makes no sense at all. 

```php
Piwik::api('Events.getCategory', [
    ... // some params that does not matter for this example
    'segment' => 'eventAction==ViewScreen;eventCategory==ContractSigned',
    'secondaryDimension' => 'eventName'
]);
```

You should think that the above code would filter through all the events and only show events that 
1. have  eventAction `ViewScreen`
2. have eventCategory = `ContractSigned`

In 3.11 we get a list of 30 events matching , but in 3.12 - we get a list of all events (1000+)?
I dont follow how this cannot be a bug.  Are we sure this is the behaviour we want?

**Comment by tsteur** [comment]
@viezel this is really the correct behaviour and how segmentation should work. You're really more after a filter here which we don't really have yet in Matomo except for custom reports.

**Comment by viezel** [comment]
@tsteur I see. Then please let me know how you will only data with these 2 conditions I showed?

because **filter_pattern** cannot do that, so I cannot see how to achieve this now

**Comment by tsteur** [comment]
> Then please let me know how you will only data with these 2 conditions I showed?

You would either need to manually filter this data if that's an option (possibly not since you have two different segments applied and you probably wouldn't get the data you want) or you use [custom reports](https://plugins.matomo.org/CustomReports) where you can apply a filter.

I totally understand this is frustrating. This is how people expect segmentation to work and unfortunately we don't have yet such a filter feature in core that you are after.

**Comment by viezel** [comment]
But Filters must be top priority for you in next release, right? 
I really don’t know any software platforms that takes fix/changes features with the argument “we don’t support this anymore”. 
Even through we have custom reports, it will takes days to regenerate reports going back in time. It’s not really a valid solution for ongoing businesses. 

We at Napp really like the mission and product of Matomo, but this move is really bad. It’s not even considered a breaking change in your changelog 😳

**Comment by viezel** [comment]
![4CA3BFCF-6189-4264-B94F-505AEAE150F0](https://user-images.githubusercontent.com/312065/71031704-32966100-2114-11ea-91f3-7294c2695e25.jpeg)
Your ads even talks about filtering with segments 🤷🏻‍♂️

**Comment by tsteur** [comment]
You can filter reports through custom reports and through our API filters but in that it won't work indeed. 

You can restore the old behaviour immediately by setting `enable_segments_cache = 0` in your `config/config.ini.php` see my comment in https://github.com/matomo-org/matomo/issues/15163#issuecomment-554555847 We've added this setting in case someone really wants that old behaviour instead of just removing the old way altogether.
