### ISSUE TITLE
Support webpack instead of relying solely on JShrink

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#15190]
In order to support using TypeScript, Angular and a better less compiler in the future we should consider allowing webpack in the development workflow.

A possible way to do this would be to run webpack on build via some sort of build-js command. this would be run by matomo-package when generating the default matomo package, and for plugins on the marketplace when deploying new versions. (Doing it this way means we don't have to require node on users' machines.)

Using it for less compilation is generally more of an issue since it would break theming.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
