### ISSUE TITLE
E-Mail Reports: Segmented Page view count too high

### ISSUE THREAD

**Issue by chris246** [matomo-org/matomo#15211]
Hi,

with the latest Matomo version 3.13.0, an E-Mail report (PDF) segmented by URL (URL starts with) contains incorrect data: Also data from URLs not starting with the given URL are included.

This is visible in the Diagram "Aktionen - Kernmetriken" (Actions - Main Metrics?) in the page count (which is too high) and the listing of page titles (which includes pages not starting with the specified URL).

**Comment by tsteur** [comment]
@chris246 this is expected behaviour since fixing https://github.com/matomo-org/matomo/issues/11900 

There is a workaround to restore the old behaviour see https://github.com/matomo-org/matomo/issues/15137#issuecomment-552571872 

We understand this may be frustrating that this behaviour changed but there is no way for us to make the behaviour right for everyone.

**Comment by chris246** [comment]
Thanks.
Sorry for the duplicate, I did not find the related issues.

**Comment by viezel** [comment]
@chris246 See https://github.com/matomo-org/matomo/issues/15438. Lets upvote it, so we can get this fixed.
