### ISSUE TITLE
Email report for a specific page url

### ISSUE THREAD

**Issue by Tim197** [matomo-org/matomo#15341]
Few days ago we updated matomo from 3.11 to 3.13.
Afterwards a user, who has an active email report running, got the report for several pages instead of only one page as before. Were there any changes made in 3.12 or 3.13? I couldn't find a relevant change.

If not - is it possible to get a report only for a specific page url? We already have a segment which filters on this one url but it still shows the other url's. 

![image](https://user-images.githubusercontent.com/59436394/71662215-f6d4db80-2d50-11ea-883e-f5859b83abfd.png)

![image](https://user-images.githubusercontent.com/59436394/71662264-24218980-2d51-11ea-9f6e-cb9d6615d7f8.png)

Thanks in advance for your help!

**Comment by tsteur** [comment]
Yes, there was a change indeed. We fixed https://github.com/matomo-org/matomo/issues/11900 which implements correct segmentation behaviour.  We understand some users may expect different behaviour for their specific use cases which is why you can restore the old behaviour or there are workarounds see https://github.com/matomo-org/matomo/issues/15130#issuecomment-551252343

**Comment by viezel** [comment]
@Tim197 I have added a FR to address this issue here https://github.com/matomo-org/matomo/issues/15438. Lets upvote it, so we can get this fixed.
