### ISSUE TITLE
Fatal Error : Variable "dbipLiteUrl" does not exist.

### ISSUE THREAD

**Issue by NicolasKulka** [matomo-org/matomo#15359]
The following error just broke Matomo (v3.13.1-rc1):

Variable "dbipLiteUrl" does not exist.
in /var/www/piwik/plugins/UserCountry/templates/adminIndex.twig line 21

Go to Settings > System > Geolocalisation

**Comment by NicolasKulka** [comment]
After update Matomo to beta version

**Comment by tsteur** [comment]
@diosmosis can you maybe have a look? I suppose that seems to happen when it thinks that GeoIP is not enabled in the controller?

BTW noticed we might also want to escape the `dbipLiteUrl` in the twig template

**Comment by diosmosis** [comment]
@tsteur This can happen if using GeoIp and not GeoIp2. I fixed it on demo will put a PR up soon, but users at this point should be using geoip2. Maybe we should also add a notification prompting users in case they are still using GeoIp?

**Comment by NicolasKulka** [comment]
Thanks !

**Comment by NicolasKulka** [comment]
same problem after upgrade matomo 3.13.1, how to resolve my problem ?

Variable "dbipLiteUrl" does not exist.
in /var/www/piwik/plugins/UserCountry/templates/adminIndex.twig line 21

**Comment by diosmosis** [comment]
@NicolasKulka can you install the GeoIp2 plugin? Note: this will perform an update that may take a while to run.

**Comment by NicolasKulka** [comment]
Thanks, problem resolved

**Comment by tsteur** [comment]
@diosmosis should we reopen the issue to prevent this issue? Seems https://github.com/matomo-org/matomo/pull/15362 didn't fix it fully?

**Comment by diosmosis** [comment]
It didn't, but this error only occurs when geoip 1 is being used, and at this point I don't think anyone should be using it.

**Comment by tsteur** [comment]
I would say many people still use it. Especially when they upgrade from an older Matomo version. AFAIK we didn't auto enable geoip2?

**Comment by diosmosis** [comment]
@tsteur the problem here is we now tell people to download dbip's database, but that database only works with GeoIp2. So if a user has GeoIp 1 installed, much of our help text is not relevant. The only thing I can think to do is display "Please install the GeoIp2 plugin (note that this plugin will require a possibly long running update)."

**Comment by tsteur** [comment]
Sounds good 👍

**Comment by plastikschnitzer** [comment]
Maybe you can optimize the helping text in a way to include deactivated modules, I was using the IP2location plugin and GeoIP2 was deactivated. I was very confused because I checked your posting here and looking into my Plugin list I found GeoIP2 but the error message still appeared – it took a while to realize that GeoIP was just deactivated … ;-) :-D
