### ISSUE TITLE
Real time map dialog box does not close with x 

### ISSUE THREAD

**Issue by plegault3397** [matomo-org/matomo#15404]
I did upgrade to the new release Matomo 3.13.1
I have seen this before.
When opening the real time map and selecting one of the dots I can review the activity. When I click on the x in the top right corner nothing happens. I can click away from the box and it does close.

**Comment by tsteur** [comment]
Indeed this no longer works. It works as a workaround when clicking on the background.

**Comment by tsteur** [comment]
This is actually not a regression. At least it's not working in 3.13 either and it doesn't look like this has been changed in a while. Will move it into 4.1 release.

The issue seems around https://github.com/matomo-org/matomo/blob/3.13.1/plugins/Live/javascripts/visitorProfile.js#L79

Quickly spent 15 min trying to fix it by adding code like this

```js

                if (self.$element.closest('#Piwik_Popover').length) {
                    Piwik_Popover.close();
                }
```

but I think this could have side effects maybe. Then thought maybe 

```js

                if (self.$element.closest('#Piwik_Popover').length) {
                    self.$element.closest('#Piwik_Popover').dialog('close');
                }
``` 

is maybe a better solution but not sure if this would confuse the popover stack etc. Not sure what the best solution is there/

**Comment by sgiehl** [comment]
@tsteur  It's actually easy to fix. The problem is, that when opening the visitor profile from the map it's directly opened within the popover, without using the url hash. In that case a simple `Piwik_Popover.close()` works. But when the url hash is present (e.g. from visitor log), that shouldn't be done.
I'll prepare a quick fix for that. Will target `3.x-dev`, let me know if that's fine. Otherwise I'll rebase it to target 4.x-dev instead.

**Comment by plegault3397** [comment]
I just mentioned it as an information, it is not an issue for me to click around to close it out. It can wait for 4.x
