### ISSUE TITLE
Development contribution

### ISSUE THREAD

**Issue by limitstudios** [matomo-org/matomo#15455]
Hi,

I would like to help contribute to matomo it's a great product to use. However I have a few questions the devs maybe able to help with.

I'm specifically looking to improve compatiblity with PHP 7.2+ i.e. (#15451) and then add some more functionality to the ecommerce tracking (which myself and my clients use alot) and I'm looking where to start, is there any developer documentation, or settings to enable a full debug mode?

I'm looking to use Xdebug and Blackfire to dig deeper into Matomo's php execution, happy to chat with devs via email, slack, etc...

**Comment by Findus23** [comment]
Hi,

You are probably looking for https://developer.matomo.org/guides/getting-started-part-1

**Comment by limitstudios** [comment]
Great thank you @Findus23

**Comment by limitstudios** [comment]
When looking at fixes should I target the 3.x or 4.x branch as not sure what the plans are in regards to PHP minimum version for each branch

**Comment by Findus23** [comment]
Any major change should be made against 4.x (minimum PHP version 7.2 or 7.3). If it is a bugfix that should also be applied in the next bugfix release also create it against 3.x (minimum 5.5.x)

**Comment by tsteur** [comment]
BTW bit hidden but there are more "in depth" docs here: https://developer.matomo.org/piwik-in-depth . For 3.x we would indeed mostly only accept regressions or important bug fixes as we're started working on 4.x a while back as @Findus23 mentioned. Re communication ideally we communicate on an issue or PR. Email we're trying to avoid when possible but could switch over to email if needed later. We otherwise also have a category for this purpose in the forum if there are particular questions: https://forum.matomo.org/c/plugins-platform 

I'll close the issue for now but feel free to comment on the issue and we can further discuss.
