### ISSUE TITLE
Comparing Sements against goals seems broken

### ISSUE THREAD

**Issue by voarsh2** [matomo-org/matomo#15510]
I'm running the latest version of Matomo (3.13.1).
I'll keep this brief.

If I go to goal overview and go to a segment, I get results that I expect.

If I compare a segment against all data or another segment, I don't get the same results.

Here's an example of just one segment in goal overview:
![image](https://user-images.githubusercontent.com/60437695/73709766-e6ba6e00-46f9-11ea-911b-98f8978b90b3.png)
![image](https://user-images.githubusercontent.com/60437695/73709791-f5a12080-46f9-11ea-87ec-e0d3eb192a7d.png)

Here's a comparison:
![image](https://user-images.githubusercontent.com/60437695/73709984-8c6ddd00-46fa-11ea-88ae-57f42daa6378.png)

Notice Social has 26 conversions, but logging has ZERO, but in the other screenshot it had ONE

If I compare multiple segments in goals, it gets even weirder:
![image](https://user-images.githubusercontent.com/60437695/73710087-ea022980-46fa-11ea-9a3a-8276f42f4bc8.png)
(Notice not even the 1 conversion from LOGGING shows on the graph)
(this screenshot is showing you that webdashboard HAS data, but isn't shown when comparing)
![image](https://user-images.githubusercontent.com/60437695/73710127-0b631580-46fb-11ea-9f46-1717d5cfe1cd.png)

As you can imagine, it's frustrating to have to go into each segment individually to get the data when comparing doesn't work properly.

I'm also uncertain if there's a bug in the latest release. Referral tracking stopped working on the 16th (when this version was released)
I had to do some funky js tweaks to make "new tab" links set the outbound link since Matomo stopped tracking it as a referral.

**Comment by tsteur** [comment]
@voarsh2 

this works for me

![image](https://user-images.githubusercontent.com/273120/74898151-ec080000-53fd-11ea-8815-6517e2a0706d.png)

Can you let me know the exact steps to reproduce this issue? I suppose it's also still there in 3.13.2?

**Comment by mattab** [comment]
@voarsh2 Thanks for the report. I think this bug has been fixed since as I haven't seen this issue recently. 

If you can reproduce the bug on the demo here: https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday&updated=1#?idSite=62&period=month&date=2020-05-28&segment=media_spent_time%3E%3D1&category=Goals_Goals&subcategory=General_Overview&compareSegments%5B%5D=visitorType%3D%3Dreturning 

or in your Matomo using latest version,  feel free to re-open this issue and we'll investigate further. Thanks
