### ISSUE TITLE
Demo.matomo.org does not show correct data

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15527]
Issue reproduced on the demo: https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62&updated=2#?idSite=62&period=week&date=2020-02-01&category=Referrers_Referrers&subcategory=General_Overview
This issue is visible to everyone on the demo it seems (in a private browser window)
but i could not reproduce it on other instances.

Here is how it looks:

![Screenshot from 2020-02-07 13-18-58](https://user-images.githubusercontent.com/466765/73989931-6a9b8100-49ac-11ea-9fed-af42275caa53.png)

* Got evolution graphs showing "Clicks" metrics for Direct entries and Total
* Expected instead evolution graphs showing "Visits" metrics for Direct entries and Total

What could cause such an issue of plotting the wrong metrics?

I could try to [run the SQL in this FAQ](https://matomo.org/faq/troubleshooting/faq_21433/) for "anonymous" user but I expected that anonymous would never get any setting stored (as the settings are expected to be stored in each anonymous' user session)

**Comment by mattab** [comment]
Actually the issue also impact other reports that show "Clicks" instead of "Visits":

![Screenshot from 2020-02-07 13-22-07](https://user-images.githubusercontent.com/466765/73990074-e269ab80-49ac-11ea-85d6-530d3d235c5e.png)
 
at https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62&updated=2#?idSite=62&period=week&date=2020-02-01&segment=&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll


or event the Visits log seems broken:
https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62&updated=2#?idSite=62&period=week&date=2020-02-01&segment=&category=General_Visitors&subcategory=Live_VisitorLog

![Screenshot from 2020-02-07 13-24-03](https://user-images.githubusercontent.com/466765/73990142-2066cf80-49ad-11ea-9513-98a68df9ed3f.png)

**Comment by tsteur** [comment]
@mattab this is only happening for ProxySite as mentioned the other day. Not for a regular site.

**Comment by tsteur** [comment]
BTW It looks like this regressed as part of 3.13.1, not 3.13.2 still looking into things

**Comment by tsteur** [comment]
FYI @diosmosis it is caused by https://github.com/matomo-org/matomo/commit/2915d75f69f2340ee6dcf1a9f4401b658fb8c966 the change from `disable_datatable_post_processing ` to `disable_root_datatable_post_processor ` https://github.com/matomo-org/matomo/blame/3.x-dev/core/Plugin/Visualization.php#L336

and I think as a result column names are not replaced for example but I suppose this might be only one of the side effects. Can you maybe have a look?

**Comment by diosmosis** [comment]
@tsteur / @mattab Oh yes, I noticed this, I have a fix (applied to demo) but I'm not sure if there will be any side effects. ProxySite's UI tests aren't working anymore (possibly due to 4.0 in some way).

**Comment by tsteur** [comment]
👍 I think eg the actions report does now show data. The visitor log still doesn't by the looks? https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&segment=&category=General_Visitors&subcategory=Live_VisitorLog

**Comment by tsteur** [comment]
BTW not sure it is a side effect or related... but looks like maybe sorting doesn't work correctly anymore? 
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&segment=&category=General_Visitors&subcategory=DevicesDetection_Software

Seems to be sorted by label instead of unique visitors? 
![image](https://user-images.githubusercontent.com/273120/74208448-78bd0a80-4ce8-11ea-96f0-da0a11f9b94e.png)

**Comment by diosmosis** [comment]
That's annoying, too many side effects. The issue is that Archive.php queues some filters to every report, but w/ `disable_root_datatable_post_processor`, they are no longer applied in the target. Removing `disable_root_datatable_post_processor` would of course break something else. I wonder if we're at the limit of what ProxySite can do given matomo's current architecture.

**Comment by tsteur** [comment]
Yeah that's possible. Not using `disable_root_datatable_post_processor ` was breaking some comparison feature I suppose?

**Comment by diosmosis** [comment]
Yes, possibly pivotBy too. I can't remember the details, but they involved ViewDataTable and were somewhat confusing.

**Comment by mattab** [comment]
The demo now looks good and working, even sorting seems to work for me? 

Thanks!

**Comment by diosmosis** [comment]
@mattab I only modified some code in demo, it will require a PR, but I found another comparison issue locally.
