### ISSUE TITLE
document how heart beat timer works since 3.13.0

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#15612]
https://github.com/matomo-org/matomo/pull/15058 made it work more efficiently, but now it isn't intuitive anymore as one can't see it do its thing when just quickly testing the website.

Therefore at least https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page and maybe also related FAQs need to be updated to properly describe how it works and how to test if it is set up correctly.

**Comment by tsteur** [comment]
@Findus23 created https://github.com/matomo-org/developer-documentation/pull/334

**Comment by sigtm** [comment]
Sorry to bring up this old issue @tsteur, but it is still unclear to me if/how `Live.getCounters` was affected by the new heartbeat logic. In our app I can see that if I leave a tab open and in focus, our live counter goes back to 0 after a while if I don't do anything. This is with the heartbeat timer enabled.

I seem to remember that the old heartbeats would also keep you counted as a live visitor until you left the page/tab, but I am not 100% sure. Am I just imagining things?

If this is as intended, I would love it if the docs mentioned how the heartbeat timer relates to the numbers given by `Live.getCounters`. Is the idea that we have to manually send `ping` requests to keep extending the visit, if we rely on the live counter? And if we do, is the heartbeat timer still needed?

**Comment by tsteur** [comment]
@sigtm this was changed a few years ago already AFAIK. We're not updating the visit time when a ping request is set as many people ended up having visit lengths of several hours because the visit basically never expired. If you wanted that behaviour you could try this with a custom plugin as suggested in https://github.com/matomo-org/matomo/issues/15179#issuecomment-557259371

**Comment by sigtm** [comment]
@tsteur Yeah we have that plugin on our end, but the Live counter still "forgets" about visitors who are on a page but not triggering any requests. Our use case centers around video streaming, so people are often on a page for a long time without triggering anything.

So `onExistingVisit` should fire regularly even with the new "heartbeat-less" heartbeat logic? If so I will just dig around a bit more on our end and see if I can figure out.

**Comment by sigtm** [comment]
@tsteur For what it's worth, sending `ping` requests explicitly fixes our Live counter numbers.

Our version of that plugin does have a `$request->getParam('ping') == 1` check – not sure if that affects the heartbeat feature? I would assume `onExistingVisit` simply doesn't fire every 15 seconds like it used to, since the heartbeat no longer triggers pings. But I haven't been able to test that theory, since the back-end is way outside my area of expertise.

**Comment by tsteur** [comment]
BTW if you are having a lot of video then [Media Analytics](https://plugins.matomo.org/MediaAnalytics) should do the trick for you.

If the problem is otherwise that the ping is not triggered, then something like this might help:

```js
setInterval(function () {.
window._paq = window._paq || [];
window._paq.push(['ping'])
  }, 15000);
```

**Comment by sigtm** [comment]
Our use case is extra niche since our technology is usually integrated into a player that we don't control  – we are essentially tracking an isolated web view, not the player/media itself.

But there are some cases where we do provide the player as well, so thanks for the tip. I will check that plugin out!

And yeah that snippet is essentially what I ended up doing 👍 Might be worth updating the part about `enableHeartBeatTimer` here?

https://developer.matomo.org/api-reference/tracking-javascript

Since it is no longer accurate to say that it "regularly sends requests", which changes the `Live.getCounter` results if you are using the reporting API.

**Comment by tsteur** [comment]
Thanks @sigtm removed the "regular"
