### ISSUE TITLE
Warning message: Key "totalUniquePageViews" for array does not exist.

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15698]
From email report:

I have replaced all of the files with the latest ones from the matomo.zip downloaded straight from the website, and the issue continues.

Key "totalUniquePageViews" for array with keys "visitorId, hasMoreVisits, totalVisits, totalVisitDuration, totalGoalConversions, totalConversionsByGoal, totalEvents, hasLatLong, lastVisits, nextVisitorId, previousVisitorId, totalVisitDurationPretty, userId, firstVisit, lastVisit, visitsAggregated, devices, continents, countries, customVariables" does not exist.
in Z:\XAMPP\htdocs\matomo\plugins\Live\templates\_profileSummary.twig line 2

**Comment by sgiehl** [comment]
Can't see a case where that could happen. It's actually the first variable used in that template. But it's always initialized for a profile within the Actions plugin. 
Did he maybe disable the Actions plugin? 🤔

**Comment by SeiRruf** [comment]
> Can't see a case where that could happen. It's actually the first variable used in that template. But it's always initialized for a profile within the Actions plugin.
> Did he maybe disable the Actions plugin? 🤔

I am the one in question here. I would never willingly disable a plugin of sort, but after seeing your reply (and being unable to fix it myself) I went ahead and checked. Sure enough, somehow, the Actions Plugin was not active. I with all honestly have no idea how this happened, but I re-enabled it and whella, issue fixed!

I think in the future, instead of throwing an error, the platform should alert that a required plugin is not installed. This would have been a ton more helpful instead of allowing individual plugins to be removed, when other plugins rely on them.

Thank you very much for the help!!! Stay safe out there. (:

**Comment by tsteur** [comment]
Thanks for letting us know @SeiRruf  Stay safe.
