### ISSUE TITLE
Error in Matomo (tracker): Invalid idSite: '0'

### ISSUE THREAD

**Issue by dimitrispie** [matomo-org/matomo#15700]
I found the following errors in the log file when I try to import logs to Matomo 3.12.0:

[Mon Mar 16 14:56:26.176472 2020] [php7:notice] [pid 13028] [client xxx.xxx.xxx.xxx:44512] Error in Matomo (tracker): Invalid idSite: '0'
[Mon Mar 16 14:56:26.790345 2020] [php7:notice] [pid 12982] [client yyy.yyy.yyy.yyy:53714] Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '9222222' ., referer: http://localhost:4200/admin/registrations?requestSortBy=registrationdate&order=DESCENDING&page=0&size=25

**Comment by Globulopolis** [comment]
Same errors in php error log

> [10-Mar-2020 09:52:23 UTC] Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '8' .
> [10-Mar-2020 09:52:24 UTC] Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '10' .

Site ID can be different.

**Comment by tsteur** [comment]
I suppose your site is still tracking in general? Make sure you always configure a siteId in your tracking code. Otherwise it would use `0` and the tracking wouldn't work. Also different siteIds could be technically set by anyone, eg `9222222` and they could be sending false tracking requests to your Matomo. Maybe double check that these IDs aren't set by your site or application. If that's all good, then you can ignore these.
