### ISSUE TITLE
YouTube-Player progress bar affected by Matomo

### ISSUE THREAD

**Issue by tom275** [matomo-org/matomo#15721]
The progress bar of the YouTube player is not working when Matomo options are set and tracking is on.

Then the event onStateChange is not working anymore. Possibly Matomo does not add its event listeners, instead it sets only its own and thus cancelling others.

Attach you can find a minimal demo page to show the effects.

Best regards,
Tom
[debug.zip](https://github.com/matomo-org/matomo/files/4369840/debug.zip)

**Comment by sgiehl** [comment]
I guess you are using the MediaAnalytics plugin?

**Comment by tom275** [comment]
Yes, that's right!

**Comment by sgiehl** [comment]
ping @tsteur

**Comment by tsteur** [comment]
@tom275 Cheers for mentioning this. I can reproduce this. Could you email our support about this through shop at innocraft.com ? That would be great.

**Comment by tsteur** [comment]
Just BTW Looks like plyr is setting events as well instead of adding the event listeners see https://github.com/sampotts/plyr/blob/master/dist/plyr.js#L6154-L6263 . We've just tried it by adding the event listeners and it doesn't seem to make a difference. There may be issues that Youtube might not be able to handle multiple events or so. To be seen.
