### ISSUE TITLE
Issues with page displaying when session is expired and we do some actions on the site

### ISSUE THREAD

**Issue by hex-code** [matomo-org/matomo#15817]
![image](https://user-images.githubusercontent.com/7688409/79354002-7ecba380-7f44-11ea-84d4-649930cd7462.png)

Should it be displayed that way? This only happens when user leave tab for 30+ mins so the session cookie expired and after that he do some actions on the site without reloading the page

**Comment by tsteur** [comment]
@hex-code are you meaning the action without a previous page view? Yes that would be expected since a user doesn't always start a new session with a page view.

**Comment by hex-code** [comment]
But it saves page url at the end of the event string in this case

**Comment by tsteur** [comment]
It records on which page the event was recorded, but it would not automatically track a page view as well. I have to close this unfortunately since we have no intention to change anything there and likely even in a plugin it may be bit tricky to implement. Sorry about that! Happy to reopen though if you think I might understand something wrong here .
