### ISSUE TITLE
 WARNING: /var/www/matomo/core/Http.php(538): Notice - Trying to access array offset on value of type null - Matomo 3.13.4

### ISSUE THREAD

**Issue by Tim197** [matomo-org/matomo#15850]
Since I updated to 3.13.2 I get the following message when I open the Administration tab:

> WARNING: /var/www/matomo/core/Http.php(538): Notice - Trying to access array offset on value of type null - Matomo 3.13.4 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: systemCheckPage, In CLI mode: false)

I am currently running at 3.13.4. 
Also, my crontab for archiving doesn't work. I set it up as described in the documentation: https://matomo.org/docs/setup-auto-archiving/
Could that be linked to the warning message?

I appreciate your help. Thanks in advance!

**Comment by tsteur** [comment]
Thanks for reporting this @Tim197 Very appreciated. Seems you're not getting a response from an HTTP request, and at the same time PHP doesn't give us an error which seems rather unusual.  I supposed we'd need to trigger a generic error message there instead when this happens. There is definitely a bug in there.

The code hasn't been changed there in many years though. It might indicate something changed on your server or environment, or on the server the script is trying to reach.

**Comment by dercheffe** [comment]
Hello I get this similar error
`MYSERVERPATH/matomo/core/Http.php(538): Notice - Trying to access array offset on value of type null - Matomo 3.14.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Installation, Action: getSystemCheck, In CLI mode: false)`
since my Lets encrypt ssl certificate expired. My hoster tries to renew it. Hopefully it willm work again. Perhaps this information helps for the bug research.

**Comment by mustard123** [comment]
I solved the problem by install php-curl

```
sudo apt-get install php-curl
sudo systemctl restart apache2.service
```

This fixes the problem for me
Credit: https://forum.matomo.org/t/autoupdate-error-in-core-http-php-538/38084

**Comment by Findus23** [comment]
The same issue was reported in https://forum.matomo.org/t/warning-message-on-new-installation/39557

For whatever reason, when Matomo tries to make a HTTP request (e.g. to fetch data from the marketplace), it gets back an empty response.
Matomo then tries to display an error message with the last error that occured, but there is no error (which causes the warning you see).

You can try to install php-curl as then Matomo uses that instead of the fopen-based method and it circumvents this issue. Or you could try to find out why your server can’t do HTTP requests in PHP.

**Comment by sgiehl** [comment]
Wondering if that might be an issue with the redirect. Seems Matomo still uses `plugins.piwik.org` as endpoint, which redirects to `plugins.matomo.org`. So the initial response would be a redirect without content. Might be interesting to know if changing this line fixes the problem:
https://github.com/matomo-org/matomo/blob/3565da78bff718f201247fc2f692c0be29220fde/plugins/Marketplace/config/config.php#L9

**Comment by peterbo** [comment]
In PHP7x, error_get_last() doesn't work, when we override the error handler manually (set_error_handler), that catches the error/behaves differently. Probably a generic message would be best!
