### ISSUE TITLE
Matomo Vs Google Analytics Count Discrepancy

### ISSUE THREAD

**Issue by prashantrtuple** [matomo-org/matomo#16022]
Hello folks,

I am using Matomo along with Google Analytics. I am using Matomo Tag Manager and placed right below the **<head>** tag, the matomo implemented on highly scalable servers and no problem from server side

Config:
**DoNotTrack** disabled on both Matomo and GA 
Avoid **Bot Tracking** enabled on both Matomo and GA 

I am facing a count discrepancy between Matomo (lesser) and Google Analytics - PageView Count, Visitor Count and Session Count.

Eg: (Single day - June 1 2020)

Tool                        |        PageView.        |.           Visitors.        |.      Session.           |
-----------------------------------------------------------------------------------
Google Analytics   |         99000.             |.           45000          |.        44000           |
Matomo                  |        79000.             |.           43000           |.         51000.           |

I am aware about the **5-10% of count discrepancy** 

What is the proper solution for this Count discrepancy between Matomo and Google Analytics.

**My References :**
https://matomo.org/faq/troubleshooting/faq_50/

**Comment by tsteur** [comment]
Thanks for creating this issue @prashantrtuple . In the issue tracker we only handle bugs and feature requests and usually don't answer questions etc. Do you mind asking this question in our forum? https://forum.matomo.org/

Something to check be if some specific pages get less page views or whether some pages maybe aren't tracked because the tracking code was not implemented there etc.

**Comment by prashantrtuple** [comment]
Hi yes @tsteur, But I have posted on matomo forum and I am yet to receive the response - https://forum.matomo.org/t/matomo-vs-google-count-discrepancy/37507
