### ISSUE TITLE
Identify Same Visitor Across Domain Without 3rd Party Cookies

### ISSUE THREAD

**Issue by pashishp** [matomo-org/matomo#16297]
Our requirement is to track a particular user journey who visits different domains. Referring https://matomo.org/faq/how-to/faq_118/ 

"In some cases, it might be interesting to enable third party cookies, so that a same visitor will get the same ID across all your domains and subdomains. Matomo (Piwik) doesn’t report cross sites visits at this stage, so you will benefit from using third party cookies only if you run manual queries against Matomo database. To enable 3rd party cookies, edit your config/config.ini.php and add the following lines:

[Tracker]
use_third_party_id_cookie = 1
"

The issue with this approach is that, we have found by default Firefox and MS Edge disables third party cookie which means we do not have this id (i.e. _pk_uid) hence the visitorid is not same. This is an issue for us. Is there an alternative way to identify the same visitorid across domains without using 3rd party cookies?

Thanks
Ashish

**Comment by tsteur** [comment]
@pashishp thanks for creating this issue. Unfortunately we handle only bug reports and feature requests here but don't answer general questions. Do you mind asking this question on https://forum.matomo.org/ ?

You might otherwise look at the [UserID feature](https://matomo.org/docs/user-id/) which may help if you can identify visitors server side somehow (eg they are logged in). Also check out our FAQ https://matomo.org/faq/new-to-piwik/faq_104/
