### ISSUE TITLE
Site Search hover help bug

### ISSUE THREAD

**Issue by MISTAnalytics** [matomo-org/matomo#16374]
**What**
In the Matomo site search report, the explanation is a bit confusing. It cannot be that there are 738.755 searches in July 2020? While the 'All visits' segment shows a total of 16.655 searches?

![Search bug Matomo](https://user-images.githubusercontent.com/46724952/92079337-044ed380-edc0-11ea-8c8f-be424e267f4c.png)

**Why**
Because currently when you hover over the help section in the site search report you will see two explanations and this is confusing.

**Suggestion**
Remove the latter sentence.

**Comment by tsteur** [comment]
I can reproduce this and I'm pretty sure it's meant to say in the second sentence "0% of all 738.755 visits in Jul 2020".

**Comment by MISTAnalytics** [comment]
@tsteur,

Yes correct, this should be visits instead of searches.

**Comment by TheCrowned** [comment]
I'll take this and submit a PR :)

**Comment by TheCrowned** [comment]
So, I've nailed this down to the file `plugins/CoreVisualizations/templates/_dataTableViz_htmlTable_ratio.twig`, where the second sentence is generated by 
`{% if totalPercentage|default is not empty %}
        {% set totalRatioTooltip = 'General_TotalRatioTooltip'|translate(totalPercentage, siteTotal|number(2,0), metricTitle, periodTitlePretty) %}`

The problem is that `metricTitle` is defined earlier as 
`{% set metricTitle   = translations[column]|default(column) %}`
and is also used in the first sentence
`{% set reportRatioTooltip = 'General_ReportRatioTooltip'|translate(label, rowPercentage|e('html_attr'), reportTotal|e('html_attr'), metricTitle|e('html_attr'), '"' ~ segmentTitlePretty ~ '"', translations[labelColumn]|default(labelColumn)|e('html_attr')) %}`

Thus it looks like they cannot really be detached and whatever goes in the first sentence will go in the second as well, or am I wrong? I am wondering if that tooltip ever even worked fine, since looking bback at past commits it looks like the relevant file has always been the way it is now
https://github.com/matomo-org/matomo/commit/3f26e785f015d30d0aeea66aaf7484111b0dbfa9#diff-02df9be9bffb622de389dc42a0cd753d

(I'm having a bit of an issue with setting up a good dev environment because of #16515)
