### ISSUE TITLE
JS error in materialize in dropdown

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16370]
refs https://github.com/matomo-org/matomo/issues/16368 

![image](https://user-images.githubusercontent.com/273120/92033881-8212df00-edc0-11ea-8e25-86df9d2e17ca.png)

when calling `.dropdown`

![image](https://user-images.githubusercontent.com/273120/92033932-9c4cbd00-edc0-11ea-8ef0-731073f72756.png)

then it fails here: 
![image](https://user-images.githubusercontent.com/273120/92033997-b9818b80-edc0-11ea-8c98-0a340ccdf89d.png)

Noticed this in `?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=2019-11-28&segment=&category=Goals_Ecommerce&subcategory=MultiChannelConversionAttribution_MultiAttribution`

when I selected an attribution model

![image](https://user-images.githubusercontent.com/273120/92034077-d1590f80-edc0-11ea-8606-945849a143ff.png)

I can't reliably reproduce it so far though and things seem to still generally work so we may be able to ignore it for now. Might be some race condition or so.

**Comment by diosmosis** [comment]
@tsteur I think I found the issue here, it fails if a datatable is loading, and before it finishes loading, we re-load the datatable in some way. So:

1) datatable is starting to reload because of some change (eg, attribution dropdown changed)
2) before datatable is finished reloading, another dropdown is used, causing new reload
3) since the content for the first datatable reloaded is never added to the dom (or is added and replaced w/ a loading gif), the dropdownConfiguration dropdown fails to find a specific element, causing it to throw

not yet sure if there's a quick fix

**Comment by diosmosis** [comment]
found a quick fix
