### ISSUE TITLE
CORS access controls not applied for non-GET requests to the tracker

### ISSUE THREAD

**Issue by fmarier** [matomo-org/matomo#16380]
Matomo has a [configuration option to restrict CORS requests to specific domains]( https://matomo.org/faq/how-to/faq_18694/) and that's correctly implemented in the [CORSHandler]( https://github.com/matomo-org/matomo/blob/b09093780b6a906a0522bda2a8137ca280ab3f65/core/API/CORSHandler.php#L48-L55) in the case of `GET` requests. However, some [additional code](https://github.com/matomo-org/matomo/blob/8b21dbf2cfb06e9c9ed9ecbbd07e3b6b386bba3b/core/Tracker/Response.php#L108-L113) overrides the CORSHandler in the case of non-`GET` requests.

Unless there is a reason for bypassing the CORSHandler, it would be safer to treat all HTTP methods the same.

**Comment by tsteur** [comment]
Note: This is in the tracker context only. I'll also post the same comment in the PR just in case someone reads it.

@fmarier If we removed this then POST tracking requests wouldn't work anymore and always fallback to GET.

See eg 
![image](https://user-images.githubusercontent.com/273120/92198160-c63cd700-eec7-11ea-8418-fe62c256cb5a.png)

This is currently their on purpose and because not really any information can be retrieved from this it shouldn't be any problem.
