### ISSUE TITLE
Automatic update: Update error: Archive is incomplete: some files are missing (eg. /config/global.ini.php).

### ISSUE THREAD

**Issue by hrehfeld** [matomo-org/matomo#16477]
Trying to update from 3.13.4 to latest (3.14.1).

After clicking on "automatic update":

```
Update error: Archive is incomplete: some files are missing (eg. /config/global.ini.php).
```

The linked zip-file https://builds.matomo.org/piwik.zip  has the mentioned file, but in `/piwik/config/global.ini.php`.

**Comment by tsteur** [comment]
@hrehfeld it looks like there was some issue while extracting the file. We actually never had this issue before by the looks. Is it possible to try the update again? Or does this error happen every time? I double checked otherwise all our recent build files and they all contain the file indeed.

If it doesn't let you update again, you may need to do the manual upgrade process unfortunately which is described in https://matomo.org/docs/update/#the-manual-three-step-update

**Comment by hrehfeld** [comment]
I retried a bunch of times before reporting, no success. Now however it just worked!

I suspect that my webserver was out of space, because it's usually at 95% or so, maybe add a check?
