### ISSUE TITLE
custom reports using the new page performance metrics often show "zero" values 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16541]
Currently custom reports using the new page performance metrics are broken: they often show "zero" values for rows.

For example this custom report preview: 

* Got: Metrics `Avg on load time` and `Avg DOM competion time` are mostly zeros 
* Expected: values in these columns #2 and #3 

![Screenshot from 2020-10-07 13-31-45](https://user-images.githubusercontent.com/466765/95274224-b0914780-08a1-11eb-83d8-3b9b38118f5f.png)

Was using these settings:

![Screenshot from 2020-10-07 13-34-37](https://user-images.githubusercontent.com/466765/95274284-dcacc880-08a1-11eb-91eb-059052f2c3de.png)

Reproduced at [custom report on demo](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=26#?idSite=26&period=week&date=today&segment=&category=CustomReports_CustomReports&subcategory=CustomReports_ManageReports&idCustomReport=6)

**Comment by sgiehl** [comment]
We had closer look into this. It actually doesn't seem to be a bug and more likely works as expected. It's by design that some performance metrics may not be tracked at all depending on the tracking implementation.

The tracking is currently designed in a way, that the initial page view tracking request will only contain those performance metrics that are available at that point. Normally tracking is done before events like page load are triggered, so all metrics getting available later won’t be tracked initially. If there is a second tracking request send within this page view (like ping, contents, event, goal, …), it may contain all additional performance metrics and the page view dimensions will be updated accordingly. If no additional tracking happens, the metrics will stay empty for that page view. So it strongly depends on the tracking implementation whether all performance metrics are tracked always or not.

I have created a follow up issue to improve the implementation to automatically send a ping request, once all performance metrics become available.
