### ISSUE TITLE
File integrity gives bad advice on symlinks

### ISSUE THREAD

**Issue by gerard76** [matomo-org/matomo#16551]
I added symlinks to matomo.js and matomo.php because matomo is a keyword that is blocked by some blockers.

File integrity is correct in pointing out they should not be there, but the solution it proposes is wrong.
<img width="578" alt="Screenshot 2020-10-08 at 13 56 40" src="https://user-images.githubusercontent.com/765547/95455797-af7a1c00-096e-11eb-8d31-a7551bc9d553.png">

Matomo 3.14.1

2020-10-10 - edit fixed typo

**Comment by tsteur** [comment]
Hi @gerard76 

I think this is actually expected behaviour and the solution be to mark these files as "to be ignored" by creating a file `config/config.php` like with content like this:

```php
<?php
return array(
    'fileintegrity.ignore' => DI\add(array(
        'w.js',
        'w.php',
    ))
);
```

If someone else can confirm this is expected behaviour then this could be put in an FAQ.

**Comment by Findus23** [comment]
I think the bug reported isn't that those files are shown, but that the check recommends deleting the original files instead of the "incorrect" symlinks.

If someone wants to fix this, they are welcome to submit a Pull Request.

**Comment by tsteur** [comment]
👍 didn't notice there was a different message. For this particular case it would actually remove those files by adding the config but of course the actual bug remains which is the use of `realpath` in https://github.com/matomo-org/matomo/blob/4.0.0-b2/core/FileIntegrity.php#L75

**Comment by aureq** [comment]
Hi @gerard76 Instead of using symlinks, may I suggest you to use [aliasing](https://httpd.apache.org/docs/current/mod/mod_alias.html) instead? This way you won't need any symlinks and you should be able to achieve what you want.

**Comment by gerard76** [comment]
Sure you may. I have no problems with the symlinks though. Just reporting a bug.

**Comment by narfk** [comment]
Another solution (Apache, .htaccess)

<IfModule rewrite_module>
	RewriteEngine On
	RewriteRule ^/w.(js|php)$ /piwik/piwik.$1 [NC,L]
</IfModule>

**Comment by danielpunkass** [comment]
I ran into this issue today and, indeed, it led to my inadvertently deleting a critical matomo source file. As @tsteur mentioned above the issue is caused because the paths are passed through `realpath` before being presented to the user. I think that a fine solution is to remove the realpath calls, because the paths, all being returned ultimately from `glob` calls, should be sufficiently canonical to make sense to the user, and to be executable on the command line. Can anybody think of a scenario where not calling `realpath` would be problematic? I'm going to submit a PR that removes these.

Tracing the history of the `realpath` calls, they go back to c8797e611e2d93808b2c70d262a816cb287a82d2, associated with #11123. Maybe @mattab can comment on whether there was a particular concern when the `realpath` calls were originally used.

If anybody is anxious about removing the `realpath` calls another option might be to run a final check before presenting a path to the user, to ensure it's not actually a path that IS part of the manifest. But with this approach the integrity checker would neglect to show the user the unexpected symlink file in the directory.

**Comment by danielpunkass** [comment]
Can somebody clarify why this was closed? I don't see any obvious commit referenced that supports it being fixed. #22723 is still open, for example.
