### ISSUE TITLE
Broken link to performance report online guide

### ISSUE THREAD

**Issue by guillaumemillot** [matomo-org/matomo#16572]
I use Matomo 4.0.0-b3.

When I click on the Performance report icon, then on "online guide" in the bottom note "Note: Some of those metrics might not always be available. You can find more information in our online guide.",
I get a 404.

Besides this small broken link issue, I'm very curious to know in which case(s) these metrics aren't available. We've upgraded this morning to 4.0.0 for that feature and these metrics aren't still available (blank) :(

**Comment by sgiehl** [comment]
Hi @guillaumemillot.
The online guide does imho not yet exist. But there is this FAQ entry https://matomo.org/faq/how-to/how-do-i-see-page-performance-reports/
Not sure if we will work on a online guide in the next weeks. Otherwise we maybe should remove or change that link. ping @mattab @tsteur 

Those metrics should actually be tracked automatically whenever the browser supports the [performance timings](https://developer.mozilla.org/de/docs/Web/API/Window/performance).

**Comment by tsteur** [comment]
@sgiehl I don't think we will create a guide for it soon so maybe we just remove the link or we link to https://matomo.org/faq/how-to/how-do-i-see-page-performance-reports/

**Comment by sgiehl** [comment]
@tsteur could we maybe forward `https://matomo.org/docs/page-performance/` to `https://matomo.org/faq/how-to/how-do-i-see-page-performance-reports/` for now, so we don't need to adjust the code again if we decide to write a guide for it?

**Comment by tsteur** [comment]
@sgiehl while it's only a visualisation that is not shown by default I don't think we will be writing a guide for it but it might eventually change once we move the page performance report into it's own subcategory in the reporting menu. I guess we could then still change the link or then redirect faq link to docs link? I can create the link if needed but prefer not to because we don't know if we ever will create one and it's easier to redirect any URL later if needed.
