### ISSUE TITLE
ERROR 1726 (HY000): Storage engine 'MyISAM' does not support system tables.

### ISSUE THREAD

**Issue by kacnje** [matomo-org/matomo#16743]
I tried to install Matomo following https://matomo.org/faq/how-to-install/faq_23484/
But when: CREATE USER 'matomo'@'localhost' IDENTIFIED WITH mysql_native_password BY 'my-strong-password-here';
I get: ERROR 1726 (HY000): Storage engine 'MyISAM' does not support system tables. [mysql.db]

Any idea? Is this only a problem with instructions?

**Comment by sgiehl** [comment]
That actually does not have anything to do with Matomo. Seems your mysql system tables have the wrong storage engine or something like that. Could be possible you did something wrong when setting up mysql in the first place.
Maybe this helps: https://stackoverflow.com/questions/54292491/how-to-fix-error-1726-hy000-storage-engine-myisam-does-not-support-system-t
Otherwise feel free to ask your question on our forum at https://forum.matomo.org.
