### ISSUE TITLE
When accessing UI with unsupported browser throw error and suggest to use other browser

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16776]
When IE 10 is used, we may want to show an exception that it is not supported instead of seeing a broken screen. This can also have security benefits since some features like `noreferrer` might not work in IE10.

**Comment by flamisz** [comment]
@tsteur when you say exception you mean really exception, like we do with other exceptions? So matomo actually can't be loaded with not supported browsers this way? That's what we want to achieve here?

Because this can be done in the `FrontController` so it will happen everywhere this way (even with the widgets).

Or we want to show an notification or warning only but let the page loaded and used by the user with not supported browsers?

Thanks

**Comment by tsteur** [comment]
An exception be fine. We wouldn't want users to be able to use it maybe since it might not be secure.
