### ISSUE TITLE
Lock down accounts by IP after N failed attemps at logging

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#2888]
Our security policy aims to make security a principal design behind Piwik. One aspect that bugs me currently is that good old brute force attacks could be vector of penetration in Piwik (if eg. attacker knows the login).

We should provide a core mechanism that would lock out, for  30min for example, a user after N failed attemps. Settings could be changed by the Super User and feature would be enabled by default, lock 30 min out after 5 failed attempts.

Implementation proposal:
- Record, using Piwik_SetOption, count of lockdown for each IP that fails to enter valid login / pwd combination
- After N failures, lock IP down and refuse authentication (even if the combination is actually valid!).
- Document as FAQ, linked from UI, the sql to delete all locked out IPs in case the SU was actually locked out and can't wait.

**Comment by jkraemer** [comment]
Actually just adding the logging (including timestamp and remote ip) might solve the whole issue for a lot of people. Fail2ban is made exactly for this purpose, there's no need to re-invent the wheel here imho.

**Comment by tsteur** [comment]
I think this is quite an important issue for security of Piwik. It is not too difficult to brute force installations otherwise.

> Lockdown IP after X attempts. Some kind of blacklist management will be need.

After eg 100 attempts within 12 hours I would lock down IP (we'd need config for this if all users come from same IP or reuse `trust_cookies` setting which is used in Intranets and depending on this disable it etc). 

> On bad credential wait X seconds before showing login screen (minimize web brute force).

After say 5 wrong login attempts for same user, I would make login slower (also on API level but won't be trivial) each time. Eg in the beginning wait 1 second, next try wait 3 seconds, next try wait 6 seconds ... This needs to be implemented wisely since one could "shut down" a Piwik under circumstances by doing wrong login requests on purpose etc. Won't be trivial to implement I reckon but I'm sure for such things there are good solutions available on the internet

**Comment by mattab** [comment]
@tsteur moved to Short term and added `Major` tag - how much effort do you think it would take to seriously mitigate this security risk?

**Comment by gaumondp** [comment]
In TYPO3 we got Backend access with a sleep(5) on bad login for 15 years. There was a discussion about brute force that could be interesting to read : 

https://forum.typo3.org/index.php/t/196184/

**Comment by tsteur** [comment]
From https://forum.typo3.org/index.php/t/196184/ :

> You will get a warning email (if you set up an address in the install tool) after four unsuccessful attempts anyway.

This could be interesting in general and useful, I'll create an issue for this: https://github.com/piwik/piwik/issues/9140

Also maybe a good read:
https://www.owasp.org/index.php/Blocking_Brute_Force_Attacks

I think a first version would be something between 1-2 days. It's really not easy I think since there are so many possibilities to workaround this and it would be possible to lock out real users.

**Comment by mattab** [comment]
FYI here is the UI for the "Limit login attempt" wordpress plugin which we use on piwik.org:

![wp limit login attemps](https://cloud.githubusercontent.com/assets/466765/10873471/2e6df040-817a-11e5-87ae-4fbb1b200d4d.png)

**Comment by ghub2015** [comment]
I have to agree with the comments that suggest just logging Piwik login attempts will be _very_ useful.

That way we can use fail2ban, or other preferred method for ratelimiting or blocking attackers.

I am still very concerned about protecting Piwik without this.

**Comment by tsteur** [comment]
FYI: There is https://plugins.piwik.org/ActivityLog which logs any login attempts etc and shows them in the UI. It is planned to show Country + IP . 

For logging the requests a PR would be appreciated 👍  It may not be too hard. @ghub2015 what kind of format would be needed for this in the logs? Or is it format independent? Asking in case someone wants to add this feature

**Comment by ghub2015** [comment]
@tsteur, being able to parse standard Apache/Nginx log format (or any other webserver), is key for fail2ban.  (In the case of Apache, it may be defined in the LogFormat stanza in /etc/apache2/apache2.conf)  

So for example, logging an HTTP status code 401 on failed login attempt would be _amazing_!

These links may be of interest:

Fail2ban and Apache:
http://www.fail2ban.org/wiki/index.php/Apache

HTTP Status code reference:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2

**Comment by mannp** [comment]
Wondered if there had been any progress on this one at all :) 

Thanks in advance

**Comment by patrickbr** [comment]
I added a simple plugin called [LoginFailLog](https://plugins.piwik.org/LoginFailLog) to the marketplace. Once activated, every failed login attempt is written to the Piwik log file like this:

```
WARNING LoginFailLog[2017-07-22 23:35:20] [b215d] Failed login from 172.217.22.227 'patrick'.
WARNING LoginFailLog[2017-07-22 23:35:20] [b215d] Failed login from 172.217.22.227 with username 'patrick'.
```

You can use this plugin to protect Piwik with fail2ban or similar tools. See the [README](https://github.com/patrickbr/piwik-LoginFailLog/blob/master/README.md) for a fail2ban example filter.

There is one problem though: Piwik [logs everything in UTC time](https://github.com/piwik/piwik/blob/9243b9a7b6fae8237596f76cda1fe8b6816463af/core/bootstrap.php#L33), for whatever reason. This is not configurable and may cause problems. For fail2ban, a workaround is described in the [README](https://github.com/patrickbr/piwik-LoginFailLog/blob/master/README.md).

**Comment by ghub2015** [comment]
@patrickbr that is awesome, thanks for this!

I will be test and give feedback.  

Let me just recommend (before even testing it) that you consider adding "Piwik" to what is logged so that it becomes:

```
WARNING Piwik LoginFailLog[2017-07-22 23:35:20] [b215d] Failed login from 172.217.22.227 'patrick'.
WARNING Piwik LoginFailLog[2017-07-22 23:35:20] [b215d] Failed login from 172.217.22.227 with username 'patrick'.
```

Just good for housekeeping/visual searching/grep'ing

**Comment by patrickbr** [comment]
@ghub2015 Everything before the "Failed login..." message is written by Piwik. The plugin uses the built-in logging system. Adding "Piwik" after "WARNING" would be redundant, as the piwik.log file only contains Piwik logs :)

**Comment by mattab** [comment]
Nice trick @patrickbr :+1: 

> There is one problem though: Piwik logs everything in UTC time, for whatever reason. 

 it seems there's an issue with our logger, as it does not log the timezone. `LoginFailLog[2017-07-22 23:35:20]` should include the timezone maybe `LoginFailLog[2017-07-22 23:35:20 UTC]` (would need to check whether this is the valid way)

**Comment by Findus23** [comment]
@patrickbr 

It seems like Fail2Ban does support UTC:https://github.com/fail2ban/fail2ban/pull/1583, https://github.com/fail2ban/fail2ban/issues/1575

But for that to work the log line needs to include the timezone as @mattab mentioned.

**Comment by patrickbr** [comment]
@mattab I created a pull request for this: https://github.com/piwik/piwik/pull/11893

**Comment by flaviusturc24** [comment]
I have a problem, I tested and it shows that IP is banned, but when I enter correct credentials, it is loggin in. What to do in this case?

**Comment by patrickbr** [comment]
@flaviusturc24 fail2ban works IP based on the connection level, it has nothing to to with your credentials. nor does it prevent you from logging in. It prevents you from even _reaching_ the server/login page. If your fail2ban log shows that your IP is banned, but you can still reach the login page, then something is either misconfigured in fail2ban, or you have some rule in your firewall that allows traffic from IP to come through, regardless of any other rule.

**Comment by mattab** [comment]
Blocked as well

**Comment by tsteur** [comment]
Of course we have thousands of options for this feature and can go crazy. But was thinking something simple in the beginning like this could do:

![image](https://user-images.githubusercontent.com/273120/45908808-8bfcdb00-be52-11e8-870a-88fd9ffd4a61.png)


Implemented some base logic in https://github.com/matomo-org/matomo/compare/2888?expand=1 but haven't tested a single line.

Basically you define how many login attempts per time range are OK. Any further login attempt within that time range will be blocked. We could also lock the IP for a specified time range after this occurred but maybe not needed in V1.

Will need to see how to make sure this check is performed independent on the auth / session adapter... Also need to perform check for `API.UsersManager.getTokenAuth`. FYI: This will also need to be executed in tracking mode and authenticated requests will result in queries. We can look into caching the results but this would result in duplicating the logic as we would need to cache the raw data more or less which is not really useful (can also count IP => attempts etc but it is not 100% the same).

These are system settings. I will need to add a feature to clear / remove some blocked IPs... because not everyone can access the server or database and delete entries (eg on a cloud hosted Matomo). Ideally the settings would be also on that page but that means we'd need to create the form to configure these settings manually, add specific APIs for them, add tests, etc.

On this page we also might show some basic stats about currently locked IPs. Won't be sending out any email notifications for now as otherwise need to keep track for which locked IPs we have sent out notifications, need to offer to receive only daily or weekly emails etc. I would add this info page under "Diagnostics".

There is also a scheduled task to keep the table size smallish...

**Comment by tsteur** [comment]
@mattab the basic logic is implemented but untested. Next step be to add tests and to ensure to run the check on all authentications independent of auth adapter.

The diagnostic page looks like this to keep things simple:
![image](https://user-images.githubusercontent.com/273120/45910076-670c6600-be5a-11e8-80ae-77c9ee2b9317.png)

If there are any objections how things work be good to know before spending any time on adding tests.

FYI: I've put all that logic into the `Login` plugin.

**Comment by tsteur** [comment]
You can find out if token is valid eg by looking at time it takes to track a request (when token is invalid it would respond faster cause an exception is triggered and no DB involved etc)... or by using bulk request maybe (not tested but I think it might report it as invalid or something).

**Comment by mattab** [comment]
There is a good reason it's not wanted to activate "Block IP for N minutes"  feature in tracking API:
* it would end up most of the time blocking IP addresses of "trusted servers" using HTTPS tracking API but having for some reason an invalid token for even a temporary time, or for other reasons. 
* An invalid token would result in the whole server IP being blocked, potentially blocking loads of other customers / websites / etc. being tracked in the same Matomo instance, and imported from the same server (using logs, SDKs, etc.), but having valid tokens. It would also block tracking api requests that don't have a token.
* An invalid token is an acceptable state and partial / wrong data is tracked (when token is wrong, data is tracked with the server IP address instead of visitor IP, for example) so there is no direct logic in blocking these requests 

At the same time we can't let people brute force and find a working token.

-> So maybe  the  solution is 1) disable this feature in Tracking API, and 2) not return errors in the Tracking API (even in bulk) so that Tracking API never leaks whether a token is valid? Then attackers have to use the Reporting API where the block IP would work.

(For Tracking API point of view, thinking the concern is also around preventing DDos/ loads of fake data. So maybe we could create another issue to introduce/reuse this IP blocking mechanism, but instead of blocking users with "too many failed token authentication", we could block IPs that send too much data over 1 hour, or 1 day, etc. This could be a nice tool to block robots, scripts, etc. storing wrong data. Currently, users have to define IP address range to block, but it's not automatic, and not retroactive, so painful if bad data has been tracked already)

**Comment by tsteur** [comment]
Currently, even a regular tracking request returns an HTTP 400 when not using correct token. This is expected so users can see something went wrong. It would be actually kind of breaking API changing behaviour there.

There would be also always still time attacks possible to find out the token.

> For Tracking API point of view, thinking the concern is also around preventing DDos/ loads of fake data

It cannot result in fake data when keeping existing tracking behaviour plus apply brute force prevention. 

DDos can happen same whether it is any API or UI request just like with the tracking reuest. 

The brute force prevention wouldn't have much effect when not applied to all authentications as an attacker naturally picks the easiest way. 

> it would end up most of the time blocking IP addresses of "trusted servers" using HTTPS tracking API but having for some reason an invalid token for even a temporary time, or for other reasons.

The same can happen to regular API requests etc. That's not much of an issue and if minutes are kept low like 30 or 60 then they won't be locked out for long. Also if needed you can always whitelist specific IPs etc.

> An invalid token would result in the whole server IP being blocked, potentially blocking loads of other customers / websites / etc. being tracked in the same Matomo instance, and imported from the same server (using logs, SDKs, etc.), but having valid tokens. It would also block tracking api requests that don't have a token.

Same applies to any API or UI request. And it would NOT block any api requests without a token.

> An invalid token is an acceptable state and partial / wrong data is tracked (when token is wrong, data is tracked with the server IP address instead of visitor IP, for example) so there is no direct logic in blocking these requests

We currently don't track data when wrong token is provided and we shouldn't. Because users wouldn't notice they are tracking wrong data.

**Comment by mattab** [comment]
New FAQ: [ How do I disable brute force authentication security checks for specific IP addresses?](https://matomo.org/faq/troubleshooting/faq_32758/)
