### ISSUE TITLE
Check Overlay feature works with js/index.php proxy

### ISSUE THREAD

**Issue by robocoder** [matomo-org/matomo#3747]
isOverlaySession
- stripping piwik.php from URL:  won't handle the js/index.php proxy
- protocol stripper won't handle a tracked page that was viewed offline (file:)

injectOverlay
- ditto on stripping piwik.php from URL

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
