### ISSUE TITLE
Support new database SQLite adaptor

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#3914]
I'm developing a new "plugin" or "how you want to be named" that allow to use SQLite instead of MySQL. Currently, works with all queries except the queries that use variables inside (@variable).

The SQLite support requires to add 2 files:
- core/Db/Adapter/Pdo/Sqlite.php
- core/Db/Schema/Sqlite.php

It's in alfa state, but I want to be usable in a short time.

If some one want to test it, please, email me to josep.sanz@saltos.net.

Josep.
Keywords: SQLite MySQL Database

**Comment by lensovet** [comment]
Would be nice to actually get this. Lack of SQLite support is literally the only reason I haven't been running piwik on some websites for 2+ years now.

**Comment by volomike** [comment]
My two cents from a seasoned developer. SQLite is a database that performs extremely well on high-speed reads, but not great at all on high-speed writes, especially writes from multiple PHP connections at the same time (which is essentially what would be happening on an active campaign). In fact, the bulk of Piwik/Matomo activities would be in writes, not reads. Reads are something it would do for checking uniqueness of a connection, and for admin activities (like getting stats in a report to see how a campaign is going). Most of the time, you want that Piwik/Matomo to be high-availability on writes or you'll start losing traffic data due to not being available. This is where MySQL, and especially PostgreSQL, performs very well. So, one may be thrilled to get it going with SQLite, but don't count on it to handle a high-volume campaign very well. You may be thrilled to see the admin interface be snappier, but at the expense of data loss for data that never had a chance to make it into the database because the SQLite database was overwhelmed with too many connections at the same time on a highly active campaign.

So, no, I don't recommend SQLite at all for this kind of project. You can learn the architecture of how SQLite saves data, versus how MySQL or PostgreSQL saves data, and see how it's functional but not fast at all. Turn it around on reads, however, and SQLite is blazingly fast against MySQL and PostgreSQL on simultaneous connections.

**Comment by lensovet** [comment]
I’m well aware of the perf impact of using SQLite vs. MySQL. I’m not looking to use Piwik on Google.com. I’m looking to use it on some internal websites that get at best 100 hits a day just to get a sense of what the most popular pages are.

**Comment by mattab** [comment]
Realistically we won't work on this ourselves in the future, so closing
