### ISSUE TITLE
Overlay, add support for custom Date range

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#4069]
When trying to view a Page Overlay for a custom date range (by manually editing the URL) the sidebar fails to load and returns an error. The page overlay works though.
# > ajaxHelper generates wrong date property when period=range
## Example

**URL**
index.php?module=Overlay&period=range&date=2013-07-02,2013-07-13&idSite=1

**Error message**
The date '2013-07-02%2C2013-07-02%2C2013-07-13' is not a correct date range. It should have the following format: 'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
