### ISSUE TITLE
Visitor Profile - Zoom map as near as possible

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#4301]
Could be useful to use the map zoom to cover all locations as near as possible to see as many details as possible.

e.g. show only Germany if all visits are from this country.

Maybe it could be even possible to make the country names clickable and on click on the country name it displays/zooms the specific country?

**Comment by mattab** [comment]
Adding Major tag as somehow this is often requested by users.

**Comment by mattab** [comment]
The automatic zooming will be awesome to have and improve user experience heaps, for people who use the maps. It's important that this feature works at least on the Real time map, but also on the general locations map.

Increasing priority for this issue since we're going to put more light on the "Real time map" in next version in https://github.com/matomo-org/matomo/pull/13414#issuecomment-420855104
