### ISSUE TITLE
Make geoip backend work with geoip2

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#4487]
do we use the best available free geo ip database from maxmind as default?

we use by default this link to get the data base:

http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

it has a file size of 10,6MB

on
http://dev.maxmind.com/geoip/geoip2/geolite2/

you could find today the Link to a free database with a size of 14,4MB

http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

=> is this an updated better Version with more/better/more accurate information in it? Or only a different format?

**Comment by joostdekeijzer** [comment]
The GeoIp2 database output is different from GeoIp1 concerning names, codes and structure.
See output [gist](https://gist.github.com/joostdekeijzer/43ce4bf48bfe42c0f688) using default test IP `194.57.91.215 `
 
As you can see, it also contains (some) translations of geographic names and the `contenent_code` for Europe has changed from "eur" to "EU".

Below are some questions to ask ourselves, but first some examples:

The city name output is:
```
[city] => Array
    (
        [geoname_id] => 3033123
        [names] => Array
            (
                [de] => Besançon
                [en] => Besançon
                // etc.
                [zh-CN] => 贝桑松
            )
    )
```

The Region Names aren't supported the way they are in GeoIp1. There now is an `subdivisions` property containing an array of area's. For above IP that's as follows; index 0 being the "biggest":

```
[subdivisions] => Array
    (
        [0] => Array
            (
                [geoname_id] => 3017372
                [iso_code] => I
                [names] => Array
                    (
                        [de] => Franche-Comté
                        // etc.
                        [fr] => Région Franche-Comté
                        // etc.
                    )
            )

        [1] => Array
            (
                [geoname_id] => 3020989
                [iso_code] => 25
                [names] => Array
                    (
                        [de] => Doubs
                        // etc.
                    )
            )
    )
```

For different countries, the devisions are different and not necessarily mapping to the GeoIp1 setup.

**What is the best way to handle these changes?**
I don't know. Some questions that I think should be answered first:

Converting the new GeoIp2 output to exisiting GeoIp1 data will be error prone, so maybe it's best to store visit-data in a new format (using the `geoname_id`'s only)?

Should current visit-data be transformed into the GeoIp2 structure?
If not, how to mix both GeoIp1 and GeoIp2 data in reports?

In https://github.com/piwik/piwik/pull/6690#issuecomment-86860922 @olavmrk suggested making a split between new installs and existing setups. Is that feasible?

Implement server support for [apache](https://github.com/maxmind/mod_maxminddb) and/or [nginx](https://github.com/leev/ngx_http_geoip2_module) ?


I'm looking forward to your comments...

**Comment by mattab** [comment]
Hi @joostdekeijzer 

it's nice to talk about this important new feature :-)
Here are some notes:

**Implementation:** I think Geoip2 support in Piwik should be implemented as a location provider just like GeoIP is currently implemented. ([code](https://github.com/piwik/piwik/blob/master/plugins/UserCountry/LocationProvider/GeoIp.php)). The implementation detail of the geoip2 location provider will be hidden in the location provider class, via the implementation of these few methods here: https://github.com/piwik/piwik/blob/master/plugins/UserCountry/LocationProvider.php#L67-135

**Admin UI:** currently users can choose in the Geo location UI to use `Default` or `GeoIP (Php)` or `GeoIP (Pecl)` or `Geoip (Apache)`. 
With Geoip2 support they could also choose for example the new `Geoip 2 (Php)` and maybe `Geoip2 (PecL)` and `Geoip2 (apache)` (not sure what options there are for geoip2)

**Data migration:** I think we don't have to worry about data migration for this task, as IMO there won't be major issue there (but maybe i'm missing something).

I hope it helps, let me know if you have any other question!

**Comment by AgentGod** [comment]
Hello, 
what is the status of the implementation of Geoip2?
Can we download and you use it?

Thanks.

**Comment by g-p-g** [comment]
From my usage I haven't noticed issues anymore.

**Comment by hpvd** [comment]
@g-p-g  are you sure you are using the enhanced database of geoip **version*2** ?

**Comment by g-p-g** [comment]
@hpvd I posted here about 1 year ago regarding this issue (you can see my comment way above). It's working for me using the latest Piwik release (not just the latest, but a few before the latest too). It's also possible that Piwik upgrades stopped reverting changes in place to get this working, which until a few version ago had to be redone after each update.

**Comment by AgentGod** [comment]
@g-p-g How did you make it work.
Previous files were .dar files and these new ones are .mmdb.
Did you made some modifications?

**Comment by g-p-g** [comment]
@AgentGod, @hpvd, and others sorry for the false hope. I mixed this with other things, the Piwik installation is in fact not using geoip2.

**Comment by AgentGod** [comment]
not good news @g-p-g  :) 
@mattab is there any ETA for implementing the option you describe in your post?

**Comment by mattab** [comment]
No ETA yet, we have not scheduled this improvement at this stage. It would be awesome if a developer from the community would issue a Pull request for this, but I understand it is a non trivial change.

**Comment by joostdekeijzer** [comment]
Hi all,

I have done some work on GeoIP2 support, but currently don't have time to continue on it. I can PR it, but it's not finished.

See:
https://github.com/joostdekeijzer/piwik/tree/GeoIP2 or more specifically https://github.com/joostdekeijzer/piwik/commit/258f7a7584af7f3c9d42bb9cc9569334fb151ed7 which is the commit to add my current implementation.

Don't forget to run `compuser update` to install the GeoIp2 code.

*Good to know*
The new GeoIp2 libraries don't support the `area_code`, so it's left empty.

*What it does do*
* Read mmdb files if properly named and put in the `/misc/` directory
* Output GeoIP info, but I've only tested by calling the API, eg: `/index.php?module=API&method=UserCountry.getLocationFromIP&ip=194.57.91.215&format=JSON` what looks fine

*Needs work on*
* tests (currently none)
  * some IPv6 addresses to test with that are "future proof" and "non IPv6-mapped IPv4"
  * Since the mmdb format is open, maybe create a small custom test mmdb with a static set of data?
* auto-update datafiles
  * The current automatic updates forms are hard-coded and only for the .dat files. It should change depending on which location provider is selected?
  * The auto-update cron function must be updated to download and test mmdb files
* speed
  * Needs testing
  * Not sure if https://github.com/joostdekeijzer/piwik/commit/258f7a7584af7f3c9d42bb9cc9569334fb151ed7#diff-663e1f37bf83d5b3c62915f859c498a7R47 is the best solution since the `city` and `country` datafiles overlap and if `city` is available probably `country` shouldn't be used.
* probably a lot more! ;-)

**Comment by berters** [comment]
+1 for this - would love to pay for a more accurate database to use with Piwik :)

**Comment by hpvd** [comment]
@berters
if you would pay for more geoip accurate data in piwik (like me!!!)
please have also a look at this ticket:
and vote for it by commenting it and asking for reopen...
https://github.com/piwik/piwik/issues/8121

**Comment by sharifhasankhan** [comment]
Can  use new GeoIP2-City.mmdb file downloaded from Maxmind and use with piwik to locate ipv4 and ipv6 ?

If anyone did it please guide with details description.

**Comment by raj45** [comment]
I also just bought the MaxMind City database, which only comes in the .mmdb format. Does Piwik support the .mmdb format?

**Comment by JHGitty** [comment]
+1 we need support for this. The old legacy geoip database say I live in HongKong but I am in Germany, lol.

**Comment by nntoan** [comment]
+1 for this. GeoLite legacy is really out of update for few (actually a lots) countries.

**Comment by Danw33** [comment]
Joining the chorus of +1's here, good to see it's still an active topic with the recent label & milestone change (thanks @mattab 👍). Looking forward to seeing this implemented! 😄 

_To others that end up here before buying a MaxMind DB:_ 
Purchasing a GeoIP2 DB also grants you access to the legacy GeoIP DB format database too - We've just purchased the GeoIP2 ISP database, and the legacy version was available and integrated with Piwik 2.16.1 just fine. (Although as previously mentioned the legacy format is a lot smaller).

**Comment by JHGitty** [comment]
Isn't the paid legacy version also heavily outdated?

**Comment by Danw33** [comment]
@JHGitty It shows as being up-to-date on their download page, although I have no way to compare the two.

<img width="775" alt="screen shot 2016-06-14 at 15 59 57" src="https://cloud.githubusercontent.com/assets/5680603/16072581/7bae1040-32d9-11e6-9e3c-99cb5801f52f.png">

**Comment by Danw33** [comment]
@JHGitty just got this week's GeoIP Organisation Legacy on our server and sure enough we're now showing in it - It's just as up-to-date as the new format one. :smile:

**Comment by mattab** [comment]
> just got this week's GeoIP Organisation Legacy on our server and sure enough we're now showing in it - It's just as up-to-date as the new format one. :smile:

that's great news!~

**Comment by hpvd** [comment]
thanks for sharing info with us!
beside it's up to date - does it also contain same amount/details of data?

The question is also does this also apply to all the other types of geoip databases?

I think even if v1 of database is ok for some cases, there is no way around making v2 usable in Piwik...

**Comment by ummelmann** [comment]
I would appreciate, if the new format would be used in piwik. Of course the legacy geolite-db is still maintained, but the new format has more granular data and so it can be more accurate in some case, but for me there is another reason, why the new format should be used: IPv6 - the legacy geolite has two seperated DBs for IPv4- and IPv6-entries - the geolite2 has tables for both address-types combined in one file. Additionally it seems, that the file-struture has become more effective, so I assume that the lookup will be faster with the geolite2.

For the integration of geolite2 into piwik you could use the page where you can choose the location-provider for the geolocation and add besides the GeoIP(php)-location-provider a new one  called GeoIP2(php) and use the GeoIP2-php-API to parse the geoip2-database-files: https://github.com/maxmind/GeoIP2-php

**Comment by hpvd** [comment]
seems to be one of the most discussed issues :-)

just to highlight what's the difference between v1 and v2: there was already a link to a nice summary posted 2,5 Years ago: https://github.com/piwik/piwik/issues/4487#issuecomment-48313707

**Comment by parruc** [comment]
Adding my +1 to the chorus. Some data from the old DB is heavily outdated/wrong.

**Comment by diabl0** [comment]
Please take a look at https://github.com/piwik/piwik/pull/10431 pull request

**Comment by hpvd** [comment]
@mattab: diabl0 did not only offer a pull request but now he also made a plugin for geoip2 support
see https://plugins.piwik.org/GeoIP2  or https://github.com/diabl0/piwik-geoip2
=> would be awesome to make Piwik benefit directly of this great work...

**Comment by sgiehl** [comment]
@hpvd correct. We told him to do so. Having stuff like that in a new plugin makes much more sense than having everything in core. Maybe it would also make sense to move the old GeoIP provider to a separate plugin in marketplace, so everone can choose which one to install.

**Comment by hpvd** [comment]
@sgiehl many thanks for explanation.
If so, the step to move also geoip1 to a plugin would make absolutely sense..
Otherwise it maybe a little confusion for piwik users how to deal with this when wanting to use geoip2, because these questions arise:
- will this geoip2-plugin will work flawlessly within piwik (which has already geoip1 integrated)
- will there be any conflicts between both
- how do I know which data piwik uses really
- do geoip2 plugin benefit from piwiks autofetch/-update for geoip1 databases
- if so how to set up...

**Comment by hpvd** [comment]
beside
- geoip2 plugin,
- geoip1 plugin,
a third plugin in this row could be
- a connection to maxmind webservice of high accurate data but on pay per use base https://github.com/piwik/piwik/issues/8121
This could make use of the official webclient (php) supporting this as a good starting point
https://github.com/maxmind/GeoIP2-php

**Comment by mattab** [comment]
Ideally, in a few months, once we have validated everything works as expected and once @diabl0 plugin is much used, we would (maybe?) integrate the GeoIP2 plugin in core, and move the GeoIP1 stuff to a plugin on the Marketplace, and we'd keep full backward compatibility so that nobody's geo location is affected. Since we don't have time to nicely handle & test all this at the moment, we proposed to make Geoip2 on the marketplace and keep geoip1 in core, for now. Hope it makes sense!

**Comment by diabl0** [comment]
> will this geoip2-plugin will work flawlessly within piwik (which has already geoip1 integrated)?

It was working as core (mentioned erlier PR https://github.com/piwik/piwik/pull/10431 ) and it's currently working without problems on my company instance using current 3.x-dev branch

> will there be any conflicts between both?

None observed, it shows as another Location Provider

> how do I know which data piwik uses really?

Check your settings - currently used location provider is marked

![zrzut ekranu 2016-09-28 10 40 24](https://cloud.githubusercontent.com/assets/2463020/18906481/ffef2c50-8567-11e6-8340-01068950f5df.png)
(on screen there are unknown values because site was accessed from intranet IP address)

You can also reattribute older data using console command:

`./console usercountry:attribute`

> do geoip2 plugin benefit from piwiks autofetch/-update for geoip1 databases?

At this time - no, but it is planned as soon as i get access to Maxmind account from my company (and this can take some time as everything in larger corporation).

**Comment by hpvd** [comment]
wow. Many thanks for these that fast and positive pieces of information!

regarding testing autofetch: the 2 free databases available also  got updates from time to time (and needs to be refreshed) :
https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by GreenReaper** [comment]
The performance characteristics of the new version may need to be tested against the legacy database. In the Java version of the GeoIP2 plugin there is [a performance issue related to text deserialization](https://github.com/maxmind/GeoIP2-java/issues/68).

Obviously Piwik is not Java, but it'd be unfortunate to see a significant regression in lookup times, especially if Piwik doesn't use most of the new data.

**Comment by s1awa** [comment]
@diabl0 your plugin is not working for me in piwik 3.0. See https://github.com/piwik/piwik/issues/11034

**Comment by grzchr15** [comment]
In our case we need accurate Maxmind and Intranet IPAM information.
As i donot see how to chain location providers currently with 
i cloned diabl0s work and added a Intranet Data loookup in front of the maxmind dbs.
So if found in the own IPAM data it takes this data. If not use Maxminf
https://github.com/diabl0/piwik-geoip2/issues/4
https://github.com/grzchr15/piwik-geoip2-andintra

**Comment by grzchr15** [comment]
Tested with Piwik 3.0.0

**Comment by AgentGod** [comment]
I am using it with latest Piwik 3.0 and seems working fine

**Comment by robertoschwald** [comment]
Old format seem to have gone now from the MaxMind website. http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz is not available anymore.

**Comment by simplusgroup** [comment]
Has anyone had any luck getting the ISP and sort data to show in Piwik? We have not yet been able to install the ISP/Org database, we have access to the new version (2) and the legacy version. We've put both types of files into the misc directory but we are still seeing "Org: Unknown ISP: Unknown".

We have been able to install the lite city database.

**Comment by mattab** [comment]
We need to bundle support for Geoip2 in Matomo very soon, ideally before April 2018, as it will stop getting updates then.

On the official page for GeoLite Legacy it says:

>  We will be discontinuing updates to the GeoLite Legacy databases as of April 1, 2018. You will still be able to download the April 2018 release until January 2, 2019. GeoLite Legacy users will need to update their integrations in order to switch to the free GeoLite2 or commercial GeoIP databases by April 2018.
> For more information, please visit our Support Center. https://support.maxmind.com/geolite-legacy-discontinuation-notice/

> In addition, in 2019, latitude and longitude coordinates in the GeoLite2 databases will be removed.* Latitude and longitude coordinates will continue to be provided in GeoIP2 databases. Please check back for updates.

(this was noted in a separate issue https://github.com/matomo-org/matomo/issues/12411 )



### Proposed steps

* Re-use the GeoIP2 plugin from the Marketplace and move it into core in our `UserCountry` plugin. 
  * ensure we have automated tests
  * update the little wizard to setup geo-location so it automatically sets up the download of the Geoip2 databases instead of legacy format.
  * add new system check to issue a warning when the "old" geolocation is used to invite users to setup GeoIP2 and still get updates
* Test that commercial city database, and also ISP, organizations databases, still work and populate the data
 * Update our user guide: https://piwik.org/docs/geo-locate/ 
 * Update all FAQs still linking to the legacy formats and referencing GeoIP v1, and also update instructions on how to use the commercial database

**Comment by hpvd** [comment]
maybe this helps some how:
https://github.com/maxmind/GeoIP2-php/releases

**Comment by robov** [comment]
Would love to the see the geoip2 support. I have it in my server logs, but not in my matomo yet

**Comment by DevDavido** [comment]
Also love to see Matomo gets an compatibility update since the very soon upcoming deprecation 👍

**Comment by mattab** [comment]
Matomo 3.5.0-RC includes Geoip2 as a separate plugin :tada: :rocket: 

Testing welcome. please enable the GeoIp2 plugin, then go to Administration > Geolocation > and select the new Geoip2 driver. Feedback welcome!

**Comment by Lozik** [comment]
I have upgraded and had the old GeoIP2-Plugin (available at the marketplace) enabled. Note that upgrading breaks the system if the old plugin is still installed. Uninstall before the upgrade. If you forgot (or didn't know), a blank page (internal PHP error) will replace the usual UI.
To get rid of the blank page:
Delete the `/plugins/GeoIP2` folder (note the big P in the filename). The Matomo UI should now load normally. Don't forget to completely uninstall the old plugin in the plugin manager in the Matomo Administration.

**Comment by kaplun** [comment]
Just performed the upgrade and stumbled upon the same issue. Would be great, for the next users who are going to upgrade, if there was a red warning about this before the upgrade, because without this GitHub issue it would have taken me some time to discover it and there would have been a long service interruption.
