### ISSUE TITLE
Feature Request: Enable "normal" admins to use segment-editor-settings

### ISSUE THREAD

**Issue by wolfstettler** [matomo-org/matomo#5801]
For a Piwik installation with a lot of websites, it is inconvenient that only super-admins can edit the settings for enable_all_users, enable_only_idsite and auto_archive in the segment editor

![piwik_segment_editor](https://cloud.githubusercontent.com/assets/2929635/3520760/c328a70e-0735-11e4-9d08-aca42dd0dbb5.png)

The normal admins can not use those features (they don't even know they exist), so there are double and triple segments with more or less the same content and often complaints about slow segments, because they are processed in real time.

I would be useful, if the admins could set these settings themselves.

Regards,
Wolf Stettler

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
