### ISSUE TITLE
Use navigator.sendBeacon by default and minimise the tracker pause from 500ms to 100ms

### ISSUE THREAD

**Issue by chaoaretasty** [matomo-org/matomo#6641]
Currently Piwik adds a delay on clicks in order to ensure the links are tracked properly. As Chrome has now shipped navigator.sendBeacon can we get it to use this instead of the delay if the browser supports it?

**Comment by tsteur** [comment]
Good news: `sendBeacon` is now supported in most major browsers but IE: https://caniuse.com/#search=sendbeacon

We should 100% give this a try and if the feature available in the browser, use it (if tests are good). This would minimize failed requests that don't make it within 500ms while at the same time not delaying the next page load by 500ms.

More information: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

**Comment by tsteur** [comment]
We could move it into 3.4 or at least 4.0?

Basically, the idea be to set a variable in the `unload` callback and then for all following (POST and / or GET) tracking requests use `sendBeacon` instead of the request XmlHttpRequest.

**Comment by tsteur** [comment]
A first implementation is done in https://github.com/matomo-org/matomo/pull/12538

However, we should also fully support this and allow users to opt in for always using `navigator.sendBeacon` if available in the browser. When enabled, we can reduce the `configTrackerPause = 500,` from 500ms to eg 100ms which makes switching between pages faster when eg a user clicked an outlink etc.

`sendBeacon` always sends a POST request. I tested it and we could send our regular GET requests via `sendBeacon` and have all parameters in the URL but this request would be still a POST. We need to check eg log importer can replace a POST request where all parameters are actually in the URL. Also we need to double check that Matomo processes such a tracking request correctly (it should I think). 

When enabled, users also need to make sure POST requests are handled correctly by the webserver. This should not be a problem.

Drawback: sendBeacon has no callback to check whether the request was successful or not.  This means the `callback` parameter won't work if someone is using the tracking API.

Universal GA supports sendBeacon since 2014 and users can opt in to it: https://www.thyngster.com/google-analytics-added-sendbeacon-functionality-universal-analytics-javascript-api/
