### ISSUE TITLE
Segments containing AND operator give no results

### ISSUE THREAD

**Issue by micvm** [matomo-org/matomo#7177]
When I use the AND operator in the segment editor for goals or urls, the result is always empty.
Piwik Version: 2.10.0 (upgraded version).

Steps to reproduce:
- Create a new segment
- Choose (e.g.) page-url equals [yourdomain])
- Add an "AND" condition
- Choose e.g. page-url equals [yourdomain]/[pagename]
  the segment will always return 0 visits.

I could reproduce the same issue by using goal-ids instead of urls:
- Create a new segment
- Choose "Visits that achieved a specific goal-id" equals [id]
- Add an "AND" condition
- Choose "Visits that achieved a specific goal-id" equals [otherid]

I tried also to combine goal with url by means of the AND operator and that does not work as well.
I can try other rules if it helps to find the problem.

**Comment by tsteur** [comment]
> Choose (e.g.) page-url equals [yourdomain])
Add an "AND" condition
Choose e.g. page-url equals [yourdomain]/[pagename] the segment will always return 0 visits.

At first I thought that's by design (and it currently is). You need an OR condition. A page URL can't be 'http://www.example.org' and 'http://example.org/pagename'. It can be only one of those. Same for goal id. You will need an OR condition there.

Maybe the design is a bit wrong as you want to see all visits that have achieved eg both goals or visited both page urls but not only one of them. Sounds like a bug to me?

**Comment by micvm** [comment]
Oh, I understand. So it's rather "actions"-based more than "visits"-based. However, I think that when piwik users filter visits with segments they may also want to know what happened within one visit in terms of combinations of actions (e.g. achieved more than one goal within a visit).

**Comment by tsteur** [comment]
True, I would want to do that as well.

ping @mattab

**Comment by mattab** [comment]
This would be nice indeed, to let us Segment to users who did a given set of actions (eg. viewed Page X + Converted Goal Y + Did Event Z). I think it's similar to Google analytics [Segment Sequence](https://developers.google.com/analytics/devguides/platform/segments#sequences).

**Comment by mattab** [comment]
see https://github.com/matomo-org/matomo/issues/7533
