### ISSUE TITLE
Add a timeout for auto-logoff

### ISSUE THREAD

**Issue by sirtet** [matomo-org/matomo#7316]
I noticed i stay logged in infinitely.
Shouldn't there be a timeout on inactivity?
Maybe with an option to change the time and/or to disable it?

**Comment by mattab** [comment]
If you click "Remember me" then you will be logged in forever. I think it's by design. Maybe we could expire it after N days of inactivity... ?

**Comment by saleemkce** [comment]
@mattab Yes, it would be better to expire user session after N days of inactivity because there is no point in keeping the user session live forever if there is no user activity in the given browser tab. We need to make the user log into the site every 3 or 5 days to make sure that the user's data is not abused by others using the same computer or device. Which would be fine, 3 or 5?

**Comment by simpleuser99** [comment]
When is issue resolve?
I need, that piwik web interface users autologout through N times.

**Comment by simpleuser99** [comment]
When the auto logoff can be resolved?

**Comment by tsteur** [comment]
@sgiehl I believe this one has been resolved a while back and users are logged out after 14 days of inactivity by default?

**Comment by sgiehl** [comment]
Yes. Afaik a session automatically ends with the browser session unless remember me is used, which extends the session to 14 days.
