### ISSUE TITLE
some API methods (eg. Goals.getGoals, Live.getCounters) are broken for multiple idSites

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#8574]
Goals.getGoals selects all goals for multiple sites, but then it will put them in an array associating each goal by its idGoal. Since goal IDs are not unique across different sites, Goals.getGoals will end up overwriting goals of other sites and not returning all goals for all requested sites.

See for example:

http://demo.piwik.org/index.php?module=API&method=Goals.getGoals&format=XML&idSite=7&period=day&date=2015-07-15,2015-08-13&date=2015-07-15%2C2015-08-13&filter_limit=false&format_metrics=1&expanded=1&token_auth=anonymous&filter_limit=30

vs.

http://demo.piwik.org/index.php?module=API&method=Goals.getGoals&format=XML&idSite=all&period=day&date=2015-07-15,2015-08-13&date=2015-07-15%2C2015-08-13&filter_limit=false&format_metrics=1&expanded=1&token_auth=anonymous&filter_limit=30

**Comment by tsteur** [comment]
See #8533 might be similar issue

**Comment by SilverNL** [comment]
Would be great if this could get fixxed? Live view all visites would be awesome..

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
