### ISSUE TITLE
Demo the awesome ecommerce functionnality

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8758]
As some of you know, Piwik offers advanced Ecommerce tracking and reporting. Piwik can track ecommerce orders, products, abandoned carts, revenue (tax, shipping, discount, etc.) and more. 

But this feature is not yet showcased on our Piwik demo at http://demo.piwik.org (oh!)

If you have a small-medium ecommerce website, and don't mind that your ecommerce data is made public, please leave a comment. It would be so nice to showcase Piwik Ecommerce features on our official [Piwik demo](http://demo.piwik.org)!

**Comment by mattab** [comment]
if you can help us with this, [please get in touch](piwik.org/contact) or leave a comment here. It would be fantastic!

**Comment by hpvd** [comment]
yes piwik is doing ecommerce tracking. Sorry I have to say this but from professional POV to be realistic, in the field of ecommerce at this time (2.1.5) piwik is **"only fine"*

To make it **"really good"** some important points are missing: features not only for documenting the things you may receive also from your shop software but to **give statitics which enable you to make good strategic decisions** on it for the future setup of your store.
e.g.
show metrics for ecommerce performance #7617
ecommerce: track more details of abandoned cart #9176
ecommerce: complete tracking of order's details #9177 

To make it **"awesome"** maybe even more unique features are needed be apart from the competition
e.g.
segment editor: make ecommerce actions accessible #9175 

**sorry again for this post**, but I think it is helping better to give true feedback instead of always saying "bravo"
Maybe this is also an important input for https://github.com/piwik/piwik/issues/6074

**Comment by Findus23** [comment]
https://demo.matomo.org is now showing complete ecommerce data, so this can be closed now.
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&category=Goals_Ecommerce&subcategory=General_Overview
