### ISSUE TITLE
One visit incorrectly reported as multiple visits in Visitor Log

### ISSUE THREAD

**Issue by rlizzi** [matomo-org/matomo#8903]
I routinely see single visits incorrect reported as multiple visits in the Visitor Log.  It appears to me that this happens when the user visits a page and then visits another page - or perhaps another instance of the same page - within one second, such that the time stamps would be the same.  Attached is a screen shot of the Visitor Log showing two occurrences of this issue, which has been going on for at least several versions.

![piwik visit bug](https://cloud.githubusercontent.com/assets/14956603/10264596/970834de-69de-11e5-943f-53a685f4a136.png)

**Comment by tsteur** [comment]
Are you using the latest Piwik version? I presume you are referring to the first 2 visitors which should be actually one visit? Such race conditions can occur, but it should happen rather very rare.

The last two are different visitors because the second one has an external referrer maybe. Maybe have a look at http://piwik.org/faq/how-to/faq_19616/

**Comment by rlizzi** [comment]
I am using version 2.14.3.

In my view, this is not at all rare; it is fairly frequent.  It sometimes happens when *I* am the visitor.

The last (bottom) visits are from the same referrer:  https://www.reddit.com/r/nationalparks/comments/3mq99m/would_you_recommend_going_to_zionbryce_right_now/cvha5vl  This is one visit, from my perspective, and this has been represented as a single visit in other cases.

**Comment by mattab** [comment]
there is a workaround available that will solve this issue of "Multiple visits created for same visitor when visitor visits the website several times in the same second" 

The workaround is to install QueuedTracking plugin and setup Redis: http://plugins.piwik.org/QueuedTracking

then all visits will bulk tracked in the API which will prevent this error. Maybe you can give it a try? unfortunately there's not  much we can do otherwise. This is similar to: https://github.com/piwik/piwik/issues/6415 https://github.com/piwik/piwik/issues/9246
