### ISSUE TITLE
Ignore cookie iframe not working when different URL is used for the tracking code than the one used for the Piwik interface

### ISSUE THREAD

**Issue by MichalTomczak** [matomo-org/matomo#9466]
In the event when different URL is used for the tracking code than the one used for the Piwik interface, the ignore cookie will not work.

**Comment by mattab** [comment]
Thanks for the report! because the ignore cookie is a third party cookie that is set on the Hostname of the "Piwik opt-out for your visitors" iframe, if the tracking server defined in the JavaScript code is a different Hostname from the iframe hostname, then the exclude cookie will not be sent to the tracking API, and user will not be ignored. 

I'm not sure how we could solve this problem as it is not technically  possible to send a cookie from another domain (ie. trusted host) in the tracking request to another host...

**Comment by tsteur** [comment]
Closing as likely not an issue anymore as we're no longer recommend using iframe opt out. Instead use the JS opt out.
