### ISSUE TITLE
Pull requests by community members: build artifacts of system tests should upload to our artifacts server

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9685]
See https://travis-ci.org/piwik/piwik/jobs/106597428#L2333

> Uploading artifacts for SystemTests...
> Invalid authentication key (1, buildEntityId = )

I think it was added recently for UI tests see https://github.com/piwik/piwik/issues/9141 but it seems to not work for system tests. The processed files were not uploaded.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
