### ISSUE TITLE
Simplify error message if user is not logged in

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9738]
See https://twitter.com/trotzendorff/status/694910789585625088

Instead we could simply write "You're not logged in" if the user is actually not logged in. Maybe there would be even no error message needed as it's kinda obvious when showing the login form.

We still need to show above error message "...requires at least 'view' access" if user is logged in, but has not access to the selected website

**Comment by mattab** [comment]
we noticed we have already a message for API `You must be logged in to access this functionality.`

**Comment by andyjdavis** [comment]
Is this issue done? I tried to jump straight to an admin area while not logged in and received the following. The displayed messages seems to have been simplified at some point since that tweet.

![login](https://user-images.githubusercontent.com/354954/107772244-f80b7100-6d76-11eb-8b79-7ae3613dd6ce.png)

**Comment by tsteur** [comment]
Thanks @andyjdavis this is done indeed 👍
