### ISSUE TITLE
Widget not found (goals, custom dimensions, custom reports)

### ISSUE THREAD

**Issue by piwikbugs** [matomo-org/matomo#9969]
I track multiple websites with Piwik. If I add some goals to my dashboard in Website A (Dashboard -> add a widget -> goals), and then change to Website B, it shows the widgets I just added to Website A as "Widgets not found" on Website B dashboard. 

Do I have to make a NEW dashboard with every website?

**Comment by tsteur** [comment]
@piwikbugs thank you for creating the issue. This is a bug. I'm not sure if we already have an issue for this but I could not find one. It won't be trivial to solve. It's almost like the dashboard needs to have knowledge which widgets depend on a idSite or something. 

I think, when two different websites have the same goalId, it will even show different goals although one might be not interested of that goal.

**Comment by mattab** [comment]
fyi: there is a similar issue if you have a "Custom Dimension" widget, and after changing the website we get an error message in the widget: "Custom dimension XYZ does not exist for this website".

**Comment by piwikbugs** [comment]
Unfortunately this isn't resolved yet. Also when I have for example 4 Goal widgets added on the dashboard of website A, all 4 are shown at website B, even if I only have one goal for website B.

**Comment by mattab** [comment]
Ideally, we will hide the widgets that do not apply to a given website,  without updating the layout stored in the DB, so that people still find the dashboard layout they expect on each website.

**Comment by mattab** [comment]
Same problem for "Custom reports" as well (updated issue title).

Reported by a customer today:

> We have several websites set up and many of these have custom reports set up.
> Each custom report is specific for the website of course.
> Now when I want to create a dashboard for a specific website the dashboard is automatically created for ALL websites.
> This is an issue as custom reports available for website A are not available for website B and vice versa. Please see below image where widget 'Lobby Visits' is available for one site but for another it is not.
> The custom reports 'Lobby Visits' exists for both sites - but they are set up separately as different settings/segments are needed for each website.
> When creating a segment we have the option to select 'only this website' or 'all'.

> · Would it be possible to add something similar for dashboards?

> Thank you very much.

**Comment by sgiehl** [comment]
This one might actually not be that easy to solve, as it's hard to define the expected behavior.
We can for sure simply give unavailable widgets a `display: none`, so they are hidden. 
But how shall we handle widgets that would be hidden on all sites. Like a removed goal or custom report. If they were hidden on all dashboard they would remain there hidden, until they get valid again. This could cause a lot hidden widgets on dashboard that never get removed.
Also it's hard to handle adding new widgets in that case. When a widget is placed in the same row as a hidden widget, the user can't se if he is placing the widget above or below. There might be more problems that could occur.

I guess a better solution would be to introduce site specific dashboards like proposed in https://github.com/matomo-org/matomo/pull/18467
Dashboards could then be made site specific as soon as a site specific widget is added.

**Comment by tsteur** [comment]
As we likely won't have https://github.com/matomo-org/matomo/pull/18467 any time soon and it meanwhile looks very buggy to have this "Widget not found" issue, the easiest would be to just hide these widgets when they weren't found. This could be implemented very quickly and be a massive improvement. I ran myself into this issue just before again thinking Matomo is buggy.
